### ISSUE TITLE
Use the debugger in Android Studio: Android Basics with Compose -- Possible missing explanation?

### ISSUE THREAD

**Issue by romerojhh** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#10]
I noticed that an explanation in the green callout section is cut off before the sentence finished. Please see attached screenshot
<img width="748" alt="image" src="https://user-images.githubusercontent.com/61641738/178135575-aeb7571e-a87c-43e9-83fe-9d65fde6bfa5.png">

**Comment by osuleymanova** [comment]
@romerojhh 
Thank you for reaching out to us and flagging this issue. The incomplete sentence is removed:

![Screen Shot 2022-07-26 at 2 48 11 PM](https://user-images.githubusercontent.com/86437155/181118416-1cd5c3c9-63ad-4877-8540-869f88b3b191.png)
