### ISSUE TITLE
Use function types and lambda expressions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by loluengo** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#101]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?hl=es-419&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Des-419%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda#4

**In which task and step of the codelab can this issue be found?**
[5. Cómo escribir expresiones lambda con sintaxis abreviada](https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?hl=es-419&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Des-419%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda#4)

Cómo omitir el nombre del parámetro

**Describe the problem**
Bad translation: "Ejecuta tu código. Kotlin reconoce el nombre del parámetro it del parámetro Int y aún imprime la cantidad de trimestres."
The last word "quarters" refers to the coins, not the academic period.  A more suitable translation could be "monedas". I would not give an academic quarter as a treat.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @loluengo 

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
