### ISSUE TITLE
Write conditionals in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Norel-Norel** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#103]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals?hl=es&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Des%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-conditionals#3

**In which task and step of the codelab can this issue be found?**

En los ejercicios
**Describe the problem**
*/cuando corro en el Playground da error
 fun main() {
   val trafficLightColor ="Ambar" 
   val message when (trafficLightColor){
        "Red" -> "Stop"
        "Yellow", "Ambar" -> "Slow"
        "Green" -> "Go"
        else -> "Ivalid Traffic-light color"
        
    }
    println(message)
}

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Norel-Norel 

Thank you for writing in with your issue.

Your code is missing an equal sign (=).

You have...
`val message when (trafficLightColor){`

You want...
`val message = when (trafficLightColor){`

Hope you are enjoying the course!

Regards.
