### ISSUE TITLE
Use nullability with Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by chrylis** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#104]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-nullability

**In which task and step of the codelab can this issue be found?**
3. Handle nullable variables → Access a property of a nullable variable

**Describe the problem**
codelab text: 
> As mentioned in a previous codelab, a compile error happens when Kotlin isn't able to compile the code due to a syntax error in your code.

> Kotlin intentionally applies syntactic rules so that it can achieve null safety, which refers to a guarantee that no accidental calls are made on potentially null variables.

Not all compile-time errors are syntax errors. Attempting to directly dereference a nullable type is not a syntax error, it is a type error.

**Comment by johnshea** [comment]
Hi @chrylis 

Thank you for taking the time to write in about this point.

I will share it with the team so they will consider it while making updates to the lesson.

Hope you are enjoying the course!

Regards.
