### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by eao29** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#105]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#3

**In which task and step of the codelab can this issue be found?**
Step 4

**Describe the problem**
It doesn't say to import the columns package, so you can't compile your code.
Needs to say you add the following import statement:

import androidx.compose.foundation.layout.Column

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @eao29 

Thank you for writing in about this concern.

The lesson has been updated to address it and it will be republished again in the near future with the fix.

Hope you are enjoying the course!

Regards.
