### ISSUE TITLE
Use the debugger in Android Studio: Android Basics with Compose

### ISSUE THREAD

**Issue by k-sameer701** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#106]
### 4. Run The Debugger

In **Attach the debugger to an app process** section.

After the **Step 1** i.e. Click  **Run ‘app'**.
The **Step 2** will be **Debug 'app'**, instead of **Attach Debugger to Android Process**.

**Comment by johnshea** [comment]
Hi @k-sameer701 

Thank you for pointing out this issue.

The lesson has been updated and will be republished again in the near future with the fix.

Hope you are enjoying the course!

Regards
