### ISSUE TITLE
Use the debugger in Android Studio: Android Basics with Compose

### ISSUE THREAD

**Issue by alghe-global** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#109]
https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-debugger?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-debugger#4

```
The Step Out button does the opposite of the Step Into button. Rather than drill down into the call stack, the Step Out button navigates up to the call stack.
```

should read

```
The Step Out button does the opposite of the Step Into button. Rather than drill down into the call stack, the Step Out button navigates up the call stack.
```

-----

```
up to the call stack.
```

to

```
up the call stack.
```

**Comment by johnshea** [comment]
Hi @alghe-global 

Thank you for bringing this to our attention.

The wording has been updated and the lesson will be republished again in the near future with the fix.

Regards.
