### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by kazi-kavish** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#11]
**URL of codelab**

[Create an interactive Dice Roller app](https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app)

**In which task and step of the codelab can this issue be found?**

In step 4 of the codelab, section: **Add a modifier**

**Describe the problem**

The code sample incorrectly contains the `@Preview` annotation.

```kotlin
@Preview(showBackground = true)
@Composable 
fun DiceWithButtonAndImage(modifier: Modifier = Modifier) {
}
````

The annotation actually belongs to the `DiceRollerApp` function as shown in the previous section:

```kotlin
@Preview
@Composable
fun DiceRollerApp() {

}

@Composable
fun DiceWithButtonAndImage() {

}
```

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**

The issue is not present in the [actual solution code](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/blob/main/app/src/main/java/com/example/diceroller/MainActivity.kt):

https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/blob/cce49feeab07410f33b535c9eac9699768f6f8c9/app/src/main/java/com/example/diceroller/MainActivity.kt#L54-L64

**Comment by osuleymanova** [comment]
Hello @kazi-kavish,

Thank you for reaching out to us and reporting this issue. The code snippet is fixed:

![Screenshot 2023-01-13 at 11 38 15 AM](https://user-images.githubusercontent.com/86437155/212404880-f3e9a33c-18a7-4079-90fb-1095abd75cc0.png)
