### ISSUE TITLE
Use function types and lambda expressions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Ignacioramirez98** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#111]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?hl=es-419&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Des-419%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda#4

**In which task and step of the codelab can this issue be found?**

task 2

**Describe the problem**

Val trickFunction = trickOrTreat(true, null) does not work, gives the error "Null can not be a value of a non-null type (Int) -> String"

**Steps to reproduce?**
1. Go to the playground de kotlin copi 
2. fun main() {
    val treatFunction = trickOrTreat(false) {"$it quarters"}
    val trickFunction = trickOrTreat(true,null)
    treatFunction()
    trickFunction()
}
fun trickOrTreat(isTrick: Boolean, extraTreat:(Int) -> String): () -> Unit {
    if(isTrick){
        return trick
    } else {
        println(extraTreat(5))
        return treat
    }
}

val trick: () -> Unit = {
    println("No treats!")
}
val treat: () -> Unit =  {
    println("Have a treat!")
}

it should be the code that we biuld during the course up to this point
3. Click on run on the playground
4. See error Null can not be a value of a non-null type (Int) -> String and no the spected 
"5 quarters
Have a treat!
No treats!
"
**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Ignacioramirez98 

Thank you for writing in.

In your code you did not change the type to nullable in the function.

You are missing...
<img width="852" alt="Screenshot 2024-03-15 at 12 24 42 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/assets/7107817/93057057-32de-40be-a671-4d57eaa514a7">

Please complete this step and try running it again.

Hope you enjoying the course!

Regards.
