### ISSUE TITLE
Art Space app: Android Basics with Compose

### ISSUE THREAD

**Issue by alghe-global** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#112]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-art-space?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-art-space#1

**In which task and step of the codelab can this issue be found?**
2

**Describe the problem**
```
You may also use a [buildAnnotatedString](https://developer.android.com/jetpack/compose/text#multiple-styles) function to apply multiple styles for a single Text composable.
```

link for `buildAnnotatedString` leads to a page not specifying any information about it

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @alghe-global 

Thank you for writing in with your observation.

The video on the linked page discusses and shows an example of`buildAnnotatedString`.

I will share with the team so they can update the lesson wording to point this out.

Hope you are enjoying the course!

Regards.
