### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by mccabe-david** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#114]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app#5

**In which task and step of the codelab can this issue be found?**
In the "Add Images" portion

**Describe the problem**
The six XML files cannot come from the same six-sided die.

**Steps to reproduce?**
1. Observe dice_1.xml, specifically how the 2-dot side orients towards the same vertex as the 3-dot side
2. Observe dice_2.xml, and notice that the sides no longer orient towards a shared vertex

**Versions**
_Android Studio version:_  N/A
_API version of the emulator:_  N/A

**Comment by johnshea** [comment]
Hi @mccabe-david 

Thank you for writing in with this observation.

You are correct and the team has been notified.

Hope you are enjoying the course!

Regards.
