### ISSUE TITLE
Use nullability with Kotlin: Android Basics with Compose > 3 Handle nullable variables

### ISSUE THREAD

**Issue by CaribbeanCoder2** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#115]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-nullability?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-nullability#2)

The second bullet item under the subheading **Use the if/else conditionals**

The first sentence reads:

"Body 1 inside the if branch assumes that the variable is non-nullable."

Should read:

"Body 1 inside the if branch assumes that the variable is not null."

The variable must obviously be of a nullable type to be doing an if/else conditional check to determine if it is null. So the assumption is that the variable is nullable but isn't set to null.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @CaribbeanCoder2 

Thank you for bringing this issue to our attention.

The lesson has been updated to address it and the fixed lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
