### ISSUE TITLE
Write conditionals in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by jtorres010** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#116]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals#2

**In which task and step of the codelab can this issue be found?**

3. Use a "when" statement for multiple branches
Write more complex conditions in a "when" statement
Use the "in" keyword for a range of conditions

**Describe the problem**

In the section that explains the use of ranges with the "in" keyword, the example shown can lead to an apparent mathematical discrepancy using values which contain decimals.

I understand this is Kotlin's normal behavior. However, it would be good to clarify that a range is not to be considered a continuous interval, but a series of individual values, or something like that. A note would be fine.

**Steps to reproduce?**

1. Go to Kotlin playground, for example.

2. Execute the codelab's example code using a number which is in the range and has a decimal part:

```
fun main() {
    val x: Any = 3.8
    when (x) {
        in 1..10 -> println("x is between 1 and 10.") // false
        else -> println("x is not between 1 and 10.") // true
    }
}
```

3. While the value 3.8 is actually in the range [1..10], the compiler returns the following output:

> x is not between 1 and 10.

**Versions**

_API version of the emulator:_ 1.9.21

**Comment by johnshea** [comment]
Hi @jtorres010 

Thank you for writing in and providing details on what you found.

I will share it with the team so they can evaluate and decide how they would like to proceed.

Hope you enjoying the course!

Regards.
