### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by vasugupta9** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#117]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#5

**In which task and step of the codelab can this issue be found?**
Step 6: Add an image

**Describe the problem**
URL mentioned below does not work. Present workaround I am using is to clone the repo to get the images.

Download the dice images
Open [this URL](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/raw/main/dice_images.zip) to download a zip file of dice images to your computer and then wait for the download to complete.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @vasugupta9 

Thank you for writing in concerning this issue.

I can confirm the link is currently working so please try again if you are able.

Hope you are enjoying the course!

Regards.

**Comment by vasugupta9** [comment]
Thanks @johnshea . Link is working now for me. 

Just as a reference - I did some search online regarding this issue. One possible reason (as per some online posts) is the internet service provider (Jio) I am using had blocked downloading raw content causing this issue.
