### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by reknoZ** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#118]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app

**In which task and step of the codelab can this issue be found?**
3. Create the layout structure
1. Remove the DefaultPreview() function.

**Describe the problem**
That function does not exist. not by that name.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @reknoZ 

Thank you for writing in and bringing this to our attention.

The lesson has been updated and will be republished again in the near future with the fix.

Hope you are enjoying the course!

Regards.
