### ISSUE TITLE
Practice problems Unit 2 Pathway 1: Android Basics with Compose

### ISSUE THREAD

**Issue by correabuscar** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#12]
A ---
name: Practice problems unit 2 pathway 1 issue template
about: Issue template for Unit 1 | Pathway 1 | Practice Problems
title: 'Practice problems Unit 2 Pathway 1: Android Basics with Compose'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-kotlin-fundamentals-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-kotlin-fundamentals-practice-problems#1

**In which task and step of the codelab can this issue be found?**
`2. Mobile notifications`

**Describe the problem**
>> *   The exact number of notifications when there are less than 100 notifications.
>> *   99+ as the number of notifications when there are more than 100 notifications.

As you can see the case when there are exactly 100 notifications isn't handled in the request.

**Comment by YaerQ** [comment]
When there are exactly 100 notifications it should still display 99+ as the number of notifications.

**Comment by osuleymanova** [comment]
@correabuscar 
Thank you for reaching out to us. The typo is fixed and published:

![Screen Shot 2022-07-19 at 10 33 08 AM](https://user-images.githubusercontent.com/86437155/179814161-62f45c18-b8d0-4d60-9ca3-81d9908a9d61.png)
