### ISSUE TITLE
Write conditionals in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by JuncProgramming** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#120]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-conditionals#0

**In which task and step of the codelab can this issue be found?**
In the "What you'll learn" step.

**Describe the problem**
The 
"How to write if/else statements."
and
"How to write when statements."
is duplicated

**Steps to reproduce?**
1. Go to...  https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-conditionals#0
2. Click on... Scroll down to "What you'll learn" step
3. See error... There should be 2 learning points duplicated

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/assets/122737448/c082bbb3-01c5-4e08-ad07-86eb7c5faa36)

**Comment by johnshea** [comment]
Hi @JuncProgramming 

Thank you for writing in with you concern.

They might look duplicated but they are not.

The first two end in "statements".

The next two end in "expressions".

Hope this clears it up and that you are enjoying the course!

Regards.
