### ISSUE TITLE
Use nullability with Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by TaymourlankFarawilla** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#122]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-nullability?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-nullability#2

**In which task and step of the codelab can this issue be found?**
Handle nullable variables in if/else expressions section

**Describe the problem**

It should use "safe-call operator" instead of "safe operator"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![2024-01-25](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/assets/156724990/4b1f192a-d162-4830-9d38-92498314d18b)

**Comment by johnshea** [comment]
Hi @TaymourlankFarawilla 

Thank you for writing in.

This has been corrected and the lesson will be republished again in the near future.

Hope you are enjoying the course!

Regards.
