### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by Romb38** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#124]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#5

**In which task and step of the codelab can this issue be found?**
Add an Image composable
When you add the painterResource

**Describe the problem**
In the codelab, you didn't explain the fact that now you need to import this libraries

```import androidx.compose.ui.res.painterResource```

And then you need to specify the field ID when you're using the painterResource like following

```painter = painterResource(id = R.drawable.dice_1) ```

**Comment by johnshea** [comment]
Hi @Romb38 

Thank you for writing in about this issue.

The lesson has been updated to address it and will be republished again in the near future.

Hope you are enjoying the course!

Regards.
