### ISSUE TITLE
Create the layout infrastructure: Create an interactive Dice Roller app: Android Basics with Compose - Wrong function name specified in Codelab

### ISSUE THREAD

**Issue by jofatmofn** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#129]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app)**

**3. Create the layout infrastructure**

Error in the document: "Remove the DefaultPreview() function." should read as "Remove the GreetingPreview() function."

**Versions**
_Android Studio version:_  Hedgehog | 2023.1.1 Patch 2

**Comment by johnshea** [comment]
Hi @jofatmofn 

Thank you for writing in about this issue.

The lesson has been updated and will be republished again in the near future with this fix.

Hope you are enjoying the course!

Regards.
