### ISSUE TITLE
Art Space app: Android Basics in Compose--------------ERROR IN ALIGNMENT....URGENT!

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#13]
**URL of codelab**

I get an error in Alignment.BottomStart.

Why?
    

**Describe the problem**

see screenshot

<img width="1440" alt="Screen Shot 2022-07-17 at 7 18 37 AM" src="https://user-images.githubusercontent.com/91148652/179397968-e5fbc37d-70e5-483d-9791-47f2b90cdb76.png">

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by YaerQ** [comment]
If I'm not mistaken Button content scope is a row so you can only use alignment available for rows like CenterVertically or Horizontally. You will need to wrap the button on either a Box, Surface or Column and then apply the alignment you want to the parent like: 
```
Box(modifier = Modifier.align(CenterHorizontally), contentAlignment = BottomCenter) {
            Button(onClick = {}, modifier = Modifier.width(100.dp)) {
                Text(text = "Next")
            }
        } 
```

**Comment by jh115424** [comment]
Ah!   Right!  Ok, I'll try that, thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
