### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by rikie** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#131]
**URL of codelab** https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%3F_gl%3D1*rzej9n*_up*MQ..%26gclid%3DCj0KCQjwhtWvBhD9ARIsAOP0Gojlpmdr1KYkWjFS8jy2ItiXB9RkcdhTcpcwFnN5ywDOohZ_UEoDMtgaAvVrEALw_wcB%26gclsrc%3Daw.ds%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app&_gl=1*187jv0l*_up*MQ..&gclid=Cj0KCQjwhtWvBhD9ARIsAOP0Gojlpmdr1KYkWjFS8jy2ItiXB9RkcdhTcpcwFnN5ywDOohZ_UEoDMtgaAvVrEALw_wcB&gclsrc=aw.ds#5

**In which task and step of the codelab can this issue be found?** Instruction to download die zip file

**Describe the problem** The url for die image download is broken, does not open. I did google search and got the correct url.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @rikie 

Thank you for writing in with your issue.

I can confirm that the link does work at this time.

Depending on where you located in the world, your results may vary.

Hope you are enjoying the course!
