### ISSUE TITLE
Write conditionals in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by techsouravganguly** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#132]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-conditionals#0

**In which task and step of the codelab can this issue be found?**
Before You begin

**Describe the problem**
In the Section Befoe you begin section-> What you'll learn->Below these two points are repeated two times
.........
How to write if/else statements.
How to write when statements.
How to write if/else expressions.
How to write when expressions.
............

**Steps to reproduce?**
1. Go to the Colab link 
2. In Before you begin section -> What you learn

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/assets/69186895/58ba2d1d-7e74-4eda-8efc-29f19310fb35)

**Comment by johnshea** [comment]
Hi @techsouravganguly 

Thank you for writing in.

The lines are not repeated but appear very similar.

Two of them end with `statements`. The next two end with `expressions`.

Hope this helps.

Regareds.
