### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by David-B-Kelley** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#134]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app

**In which task and step of the codelab can this issue be found?**
All steps

**Describe the problem**
The word "dice" is incorrectly used as if it is a singular for.  "Dice" is plural.  "Die" is singular.  The codelab only uses one virtual die so there should be no references to "dice".
See the definition of the noun "die" here: https://www.merriam-webster.com/dictionary/die

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @David-B-Kelley 

Thank you for writing in.

Per [Collins dictionary](https://www.collinsdictionary.com/us/dictionary/english/dice)..."In old-fashioned English, `dice` was used only as a plural form, and the singular was die, but now `dice` is used as both the singular and the plural form."

Hope you are enjoying the course!

Regards.
