### ISSUE TITLE
Practice problems Unit 2 Pathway 1: Android Basics with Compose

### ISSUE THREAD

**Issue by MarNiko** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#135]
Hi, my name is Facundo. Sorry for my english. Below i send you the problem i found. Very good the codelabs, i learn so much. I hope is sending this correctly. Thanks!

A ---
name: Practice problems unit 2 pathway 1 issue template
about: Issue template for Unit 1 | Pathway 1 | Practice Problems
title: 'Practice problems Unit 2 Pathway 1: Android Basics with Compose'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-kotlin-fundamentals-practice-problems?hl=es-419&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Des-419%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-kotlin-fundamentals-practice-problems#8

**In which task and step of the codelab can this issue be found?**
In the Step 8 - Special Auction

**Describe the problem**
I made my solution which works, it is quite precarious for sure because I have just started with Kotlin, but when checking with the answers in step number 9, the code provided, although it works, does not comply with what was requested, since if the bidder offers less of the minimum you are sold for what you offered, which seems to me not to be correct since a minimum price is established for a reason.

This is my solution:
class Bid(val amount: Int, val bidder: String)

fun auctionPrice(bid: Bid?, minimumPrice: Int): Int {
    if (bid != null) {
        if (bid.amount > minimumPrice) {
            return bid.amount
        }else {
            return minimumPrice
        }
    }else{
        return minimumPrice
    }
}

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @MarNiko 

Thank you for writing in.

The quiz question given was meant to give you practice coding if a value was null. It was not meant to behave as a real auction would with a minimum price as you stated.

Glad you are enjoying the course!

Regards.
