### ISSUE TITLE
Use the debugger in Android Studio: Android Basics with Compose

### ISSUE THREAD

**Issue by correabuscar** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#14]
in https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-debugger?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-debugger#4

The `Note` seems incomplete:
> Note: The result$delegate variable in the Variables pane refers to the result variable in the code. The $delegate notation is there because the result variable is a remember delegate. But the value

`But the value` is the last sentence and it's incomplete.

![but the value](https://user-images.githubusercontent.com/106607441/179811335-1851068e-7cb9-4cc2-8db0-517ca0af35c8.png)

**Comment by osuleymanova** [comment]
Duplicate of #10

**Comment by osuleymanova** [comment]
@correabuscar 
Thank you for reaching out to us. The incomplete sentence is removed:

![Screen Shot 2022-07-26 at 2 48 11 PM](https://user-images.githubusercontent.com/86437155/181118670-d1b5d877-cd94-450d-a79e-9aa5677888fe.png)
