### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by hsseek** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#19]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#2

A name of an Activity should not contain a whitespace. i.e. The name should be `DiceRollerActivity` etc, instead of `Dice Roller`.

![Android Studio New Project](https://developer.android.com/static/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app/img/aee740f64c67b12b.png)

**Comment by osuleymanova** [comment]
@hsseek 
Thank you for reaching out to us. The name of Activity could be any, as the whitespace doesn't affect anything. But there should be no whitespaces in the location path as it can cause problems with NDK tools.
