### ISSUE TITLE
Practice problems Unit 2 Pathway 1: Android Basics with Compose

### ISSUE THREAD

**Issue by mrpwilliams80** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#2]
A ---
name: Practice problems unit 2 pathway 1 issue template
about: Issue template for Unit 1 | Pathway 1 | Practice Problems
title: 'Practice problems Unit 2 Pathway 1: Android Basics with Compose'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-kotlin-fundamentals-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-kotlin-fundamentals-practice-problems#3

**In which task and step of the codelab can this issue be found?**
Task 4 - Temperature Converter

**Describe the problem**
In the provided code the names of the properties do not match the names used in the println() statement.
initialTemperature should be initialUnit; and;
finalTemperature should be finalUnit.

**Steps to reproduce?**
1. Copy code into playground
2. Complete missing code in main() function - e.g. `printFinalTemperature(27.0, "Celsius", "Fahrenheit") {9.0/5.0 * it + 32}`
3. Click on button to run
4. See errors:
> Unresolved reference: initialTemperature
> Unresolved reference: finalTemperature

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@mrpwilliams80 
Thank you for reaching out to us. The issue is fixed and will be published soon.
`fun main() {
    // Fill in the code.
}

fun printFinalTemperature(
    initialMeasurement: Double, 
    initialUnit: String, 
    finalUnit: String, 
    conversionFormula: (Double) -> Double
) {
    val finalMeasurement = String.format("%.2f", conversionFormula(initialMeasurement)) // two decimal places
    println("$initialMeasurement degrees $initialUnit is $finalMeasurement degrees $finalUnit.")
}`
