### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by hsseek** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#20]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#7

**Describe the problem**
Adopting the `remember` function throws an error.
![to import](https://developer.android.com/static/codelabs/basic-android-kotlin-compose-using-state/img/b651ccb43a6fd25.png)
So, one should import the followings.
```
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
```
I thought you might have omitted it because that is so obvious, but the [next course](https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#7) explicitly directs the user to import the libraries.

I think you should:
1. Direct the user to import the libraries at first, then omit on the next uses.
2. Direct the user to import the libraries all the time.

Instead of omitting it at first, then mention it on a later course.

**Comment by patricioconti** [comment]
Excellent comment!  Thank you.

**Comment by osuleymanova** [comment]
@hsseek 
Thank you for contacting us and sharing your feedback. It's a good practice to enable auto imports for each project from the very beginning, so in the future you won't need any reminder in the codelab:

![Screen Shot 2022-10-19 at 12 59 17 PM](https://user-images.githubusercontent.com/86437155/196792012-c744b2d5-a9ec-46a8-a299-62fbeba1dd8c.png)

The unambiguous imports settings tell Android Studio to automatically add an import statement, as long as it can determine which one to use. The optimize imports settings tell Android Studio to remove any imports that aren't being used by your code.
