### ISSUE TITLE
Practice problems Unit 2 Pathway 1: Android Basics with Compose

### ISSUE THREAD

**Issue by ruaine83** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#21]
A ---
name: Practice problems unit 2 pathway 1 issue template
about: Issue template for Unit 1 | Pathway 1 | Practice Problems
title: 'Practice problems Unit 2 Pathway 1: Android Basics with Compose'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-kotlin-fundamentals-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-kotlin-fundamentals-practice-problems#8

**In which task and step of the codelab can this issue be found?**
The temperature conversion solution code

**Describe the problem**
In the temperature conversion solutions code, there was an issue that I uncovered.  During the process of the (5/9) division, either the solution code MUST use decimal places or the toDouble() casting function. Otherwise the 5/9 results in 0 due to integer truncation. This results in the code then multiplying by 0 until adding the 273.15.

It would be helpful if someone made a note/hint somewhere in the assignment of the problem, or in the solution that one would need to ensure that the code uses decimal places as the posted solution does, or that the toDouble() cast needs to be used, otherwise the error can be hard for a new programmer to trace.

**Steps to reproduce?**
Don't use decimal places. Use the function as close as possible to the way it's written in the assignment.

**Versions**
Playground

**Additional information**
I know it's a nitpick, but for someone just learning how to code, something this simple can be REALLY frustrating, especially when the difference in what needs to be done to fix their code isn't obvious.  Depending on the person, something this simple could be just enough of a roadblock to discourage them from continuing in their journey.

This is also a good teaching moment for them to learn that logic errors are sometimes the most infuriating to trace down, and sometimes require thinking a little outside of the box.

**Comment by rafaover** [comment]
I changed the formula and the problem was solved. If that helps.
val celsius2Fah: (Double) -> Double = { 1.8 * celsiusTemp + 32 }
    val kelvin2Celsius: (Double) -> Double = { kelvinTemp - 273.15 }
    val fah2Kelvin: (Double) -> Double = { (5 * (fahTemp - 32)) / 9 + 273.15 }

**Comment by rafaover** [comment]
I received a msg: 
Expression '5' of type 'Int' cannot be invoked as a function. The function 'invoke()' is not found
Expression '9' of type 'Int' cannot be invoked as a function. The function 'invoke()' is not found
Link to the code: https://pastebin.com/R7aCVYWg
What I did to solve it changed the formula. But can you help me solving in a different way?

**Comment by jayeshmann** [comment]
I am calling the function like this
`printFinalTemperature(27.0, "Celsius", "Fahrenheit") { (9.0/5.0)*it + 32 }` OR
`printFinalTemperature(27.0, "Celsius", "Fahrenheit", { (9.0/5.0)*it + 32 })`

Hope it helps!

**Comment by sc-gds-lxl** [comment]
The solution code appears to be functioning correctly.
