### ISSUE TITLE
Practice problems Unit 2 Pathway 1: Android Basics with Compose

### ISSUE THREAD

**Issue by rafaover** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#22]
A ---
name: Practice problems unit 2 pathway 1 issue template
about: Issue template for Unit 1 | Pathway 1 | Practice Problems
title: 'Practice problems Unit 2 Pathway 1: Android Basics with Compose'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-kotlin-fundamentals-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-kotlin-fundamentals-practice-problems&hl=en#3

**In which task and step of the codelab can this issue be found?**
4. Temperature Converter

**Describe the problem**
The problem provides 3 formulas, see below: 
Celsius to Fahrenheit: ° F = 9/5 (° C) + 32
Kelvin to Celsius: ° C = K - 273.15
Fahrenheit to Kelvin: K = 5/9 (° F - 32) + 273.15

After finishing the whole exercise, 2 problems are reported in the first and third formula:
- Expression '5' of type 'Int' cannot be invoked as a function. The function 'invoke()' is not found
- Expression '9' of type 'Int' cannot be invoked as a function. The function 'invoke()' is not found

With my limited knowledge the only way that I found to solve the question and run the code was changing the formula to:
val celsius2Fah: (Double) -> Double = { 1.8 * celsiusTemp + 32 }
val kelvin2Celsius: (Double) -> Double = { kelvinTemp - 273.15 }
val fah2Kelvin: (Double) -> Double = { (5 * (fahTemp - 32)) / 9 + 273.15 }

Maybe providing the formulas in a different way could make the solution more approachable:
F = 1.8 * C + 32
C = K - 273.15 }
K = (5 * (F - 32)) / 9 + 273.15

Thank you.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by rafaover** [comment]
Maybe providing the formulas in a different way could make the solution more approachable:
F = 1.8 * C + 32
C = K - 273.15 }
K = (5 * (F - 32)) / 9 + 273.15

Thank you.

**Comment by angiesasmita** [comment]
Hello there :)

Would you be able to share the code where the error message below appears:
```
Expression '5' of type 'Int' cannot be invoked as a function. The function 'invoke()' is not found
Expression '9' of type 'Int' cannot be invoked as a function. The function 'invoke()' is not found
```

With the formula given in the question, the solution could be reached with:
```
fun main() {
    val celsiusTemp = 27.0
    val kelvinTemp = 350.0
    val fahTemp = 10.0
    val celsius2Fah: (Double) -> Double = { 9.0/5.0 * celsiusTemp + 32 }
    val kelvin2Celsius: (Double) -> Double = { kelvinTemp - 273.15 }
    val fah2Kelvin: (Double) -> Double = { (5.0/9.0 * (fahTemp - 32)) + 273.15 }
    
    printFinalTemperature(celsiusTemp, "Celsius", "Fahrenheit", celsius2Fah)
    printFinalTemperature(kelvinTemp, "Kelvin", "Celsius", kelvin2Celsius)
    printFinalTemperature(fahTemp, "Fahrenheit", "Kelvin", fah2Kelvin)
}
```

The solution accuracy might be affected if `Int` is used instead of `Double`, but this hint was also stated in the question.

**Comment by rafaover** [comment]
It was some time ago I was not using any git to follow up modifications. Replicating the code, I believe the closer was this one, using the original formula given to me.

```
fun main() {
    val celsiusTemp = 27.0
    val fahTemp = 10.0
    val kelvinTemp = 350.0
    val c = "Celsius"
    val f = "Fahrenheit"
    val k = "Kelvin"
    val celsius2Fah: (Double) -> Double = {9/5 * (celsiusTemp) + 32}  
    val kelvin2Celsius: (Double) -> Double = {kelvinTemp - 273.15}
    val fah2Kelvin: (Double) -> Double =  {5/9 (fahTemp - 32) + 273.15}

    printFinalTemperature(celsiusTemp, c,  f, celsius2Fah)
    printFinalTemperature(kelvinTemp, k, c, kelvin2Celsius)
    printFinalTemperature(fahTemp, f, k, fah2Kelvin)
}
fun printFinalTemperature(
    initialMeasurement: Double,
    initialUnit: String,
    finalUnit: String,
    conversionFormula: (Double) -> Double
) {
    val finalMeasurement = String.format("%.2f", conversionFormula(initialMeasurement)) // two decimal places
    println("$initialMeasurement degrees $initialUnit is $finalMeasurement degrees $finalUnit.")
}
```

**Comment by angiesasmita** [comment]
The formula that is stated is a mathematical formula and not in a programming language. It is given to illustrate requirement in the real world that needs to be translated to programming language when creating a working code.
