### ISSUE TITLE
Art Space app: Android Basics with Compose

### ISSUE THREAD

**Issue by chaberfeld** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#24]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-art-space?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-art-space#3

**In which task and step of the codelab can this issue be found?**
4. Challenge: Build for different screen sizes (Chapter)

**Describe the problem**
Typo. Several times word 'table' was used instead of 'tablet'.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@chaberfeld 
Thank you for reaching out to us. The typos are fixed and will be published soon.
