### ISSUE TITLE
Use nullabillity in Kotlin 

### ISSUE THREAD

**Issue by BelenSeoane** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#25]
The prerequisites of this codelab mention "knowledge of Kotlin classes, including how to access methods and properties from a variable ". The codelab featuring classes and such doesn't come for later on in the course (it's actually the next lesson). Perhaps these two lessons should be swapped places so the prerequisites for Use Nullabillity in Kotlin can be met effectively?

![Screenshot_2022-09-28-01-53-54.png](https://user-images.githubusercontent.com/62359198/192690600-9c221a6b-bb6c-448e-8055-0aa70472e994.png)

(_Prerequisites for Use Nullabillity in Kotlin. Note 3rd item_)

![Screenshot_2022-09-28-01-55-55.png](https://user-images.githubusercontent.com/62359198/192690856-e1a746d0-861f-4e84-9f3e-a12a82599097.png)

(_Codelabs in current order_)

**Comment by osuleymanova** [comment]
@BelenSeoane 
Thank you for reaching out to us. Your feedback has been taken into consideration and followed by changes in prerequisites section:
![Screen Shot 2022-10-20 at 8 40 35 AM](https://user-images.githubusercontent.com/86437155/196999851-5edabfdc-f572-4570-b269-0f288e3a24be.png)
