### ISSUE TITLE
Practice problems Unit 2 Pathway 1: Android Basics with Compose

### ISSUE THREAD

**Issue by SigmaZardan** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#27]
A ---
name: Practice Kotlin Fundamentals
about: Error in the Solution Section 9 . 
(Error in Special Auction Solution ) 

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-kotlin-fundamentals-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-kotlin-fundamentals-practice-problems#8

**In which task and step of the codelab can this issue be found?**
Task :- Error in the Solution Section 9 . 
(Error in Special Auction Solution ) 
line number :- 4 and 5

**Describe the problem**
The auctionPrice method is not accessed directly without using the object of the class Bid.

**Solution** 
Using the object of the class 'winningBid' that is created inside the main method to access the auctionPrice method as :
 println("Item A is sold at ${winningBid.auctionPrice(winningBid, 2000)}.")
    println("Item B is sold at ${winningBid.auctionPrice(null, 3000)}.")

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by sc-gds-lxl** [comment]
The `auctionPrice()` method is not part of the `Bid` class. It is accessed correctly.
