### ISSUE TITLE
Practice problems Unit 2 Pathway 1: Android Basics with Compose

### ISSUE THREAD

**Issue by byungmeo** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#28]
A ---
name: Practice problems unit 2 pathway 1 issue template
about: Issue template for Unit 1 | Pathway 1 | Practice Problems
title: 'Practice problems Unit 2 Pathway 1: Android Basics with Compose'

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-kotlin-fundamentals-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-kotlin-fundamentals-practice-problems#3

**In which task and step of the codelab can this issue be found?**
Practice: Kotlin Fundamentals -> 4. Temperature converter

**Describe the problem**
The Korean translation is wrong.

Korean Ver. (Incorrect)
println("$initialMeasurement degrees $initialTemperature is $finalMeasurement degrees $finalTemperature.")

English Ver.
println("$initialMeasurement degrees $initialUnit is $finalMeasurement degrees $finalUnit.")

**Additional information**
![image](https://user-images.githubusercontent.com/37506142/197323692-f609c2b8-01f2-42ea-b88d-3f8f8c7ae8f5.png)
![image](https://user-images.githubusercontent.com/37506142/197323651-5f5e5e51-5b7c-480c-af9e-32c37033ec1c.png)

**Comment by sc-gds-lxl** [comment]
Labeling with localization and closing as a duplicate.
