### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by vajranaga** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#30]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#3

**In which task and step of the codelab can this issue be found?**
"Create The Layout Infrastructure"

**Describe the problem**
Several code errors jumping between similar named functions, the described action does not match the code displayed, or the solution code

**Steps to reproduce?**
Follow tutorial

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @vajranaga,

Thank you for reaching out to us and sharing your concern. But could you be more specific about it?

**Comment by osuleymanova** [comment]
Closing this issue, since there is no specific description.
Please create a new one, if you need help.
