### ISSUE TITLE
Practice problems Unit 2 Pathway 1: Android Basics with Compose

### ISSUE THREAD

**Issue by ParkSangYeol** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#32]
A ---
name: Practice problems unit 2 pathway 1 issue template
about: Issue template for Unit 1 | Pathway 1 | Practice Problems
title: 'Practice problems Unit 2 Pathway 1: Android Basics with Compose'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-kotlin-fundamentals-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-kotlin-fundamentals-practice-problems#3

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
in function 

fun printFinalTemperature(
    initialMeasurement: Double,
    initialUnit: String,
    finalUnit: String,
    conversionFormula: (Double) -> Double
) {
    val finalMeasurement = String.format("%.2f", conversionFormula(initialMeasurement)) // two decimal places
    println("$initialMeasurement degrees $initialTemperature is $finalMeasurement degrees $finalTemperature.")
}

The arguments are initialUnit and finalUnit, but the println function uses initialTemperature and finalTemperature.

**Steps to reproduce?**
1. Go to...
 fun main() {
    // I wrote the main code myself.
    val celsiusToFahrenheit: (Double) -> Double = { it*9/5 + 32}
    val KelvinToCelsius: (Double) -> Double = { it - 273.15}
    val FahrenheitToKelvin: (Double) -> Double = {(it-32)*5/9 + 273.15}
    
   	printFinalTemperature(27.0, "Celsius", "Fahrenheit", celsiusToFahrenheit)
   	printFinalTemperature(350.0, "Kelvin", "Celsius", KelvinToCelsius)
   	printFinalTemperature(10.0, "Fahrenheit", "Kelvin", FahrenheitToKelvin)
}

fun printFinalTemperature(
    initialMeasurement: Double,
    initialUnit: String,
    finalUnit: String,
    conversionFormula: (Double) -> Double
) {
    val finalMeasurement = String.format("%.2f", conversionFormula(initialMeasurement)) // two decimal places
    println("$initialMeasurement degrees $initialTemperature is $finalMeasurement degrees $finalTemperature.")
}

2. See error

Unresolved reference: initialTemperature
Unresolved reference: finalTemperature

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by angiesasmita** [comment]
hi @ParkSangYeol , 

The `println` function in the question is using `initialUnit` and `finalUnit`. Could you send us the screenshot when it uses `initialTemperature` and `finalTemperature`? 
![image](https://user-images.githubusercontent.com/10851617/202081717-fa898f22-caa1-4fb7-98cc-2c00cc70662a.png)

**Comment by ParkSangYeol** [comment]
[image: image.png]
As I checked now, there was a problem with the Korean translation page. I
checked that it comes out normally on the English page.

[image: image.png]

2022년 11월 16일 (수) 오후 1:13, Angie Sasmita ***@***.***>님이 작성:

**Comment by angiesasmita** [comment]
Thanks @ParkSangYeol for pointing it out. We are working to fix this issue.

**Comment by sc-gds-lxl** [comment]
Labeling this as a localization issue because it seems to be having correctly in other areas.

**Comment by johnshea** [comment]
Hi @ParkSangYeol 

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
