### ISSUE TITLE
Write conditionals in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Joosemi02** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#33]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-conditionals#2

**In which task and step of the codelab can this issue be found?**
Use the in keyword for a range of conditions

**Describe the problem**
wrong image display

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
<img width="623" alt="image" src="https://user-images.githubusercontent.com/37875402/202253453-3e4bd151-e3ec-4047-b7c5-28ad7bb3f51e.png">

**Comment by osuleymanova** [comment]
@Joosemi02 
Thank you for reaching out to us. The broken image was fixed and published:

![Screen Shot 2022-11-17 at 4 08 39 PM](https://user-images.githubusercontent.com/86437155/202586948-dde45b8b-65d3-4b47-bb0a-da35e7e138f4.png)
