### ISSUE TITLE
Use nullability with Kotlin: Android Basics in Compose

### ISSUE THREAD

**Issue by InedibleGoose** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#35]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
It seems that the final section that introduces the Elvis "?:", fails to have one final screen to show how it handles and assigns for a "null" value. 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by sc-gds-lxl** [comment]
Could you please link the codelab and provide the exact location where you see this issue?

**Comment by osuleymanova** [comment]
@InedibleGoose 
Closing this issue, since there is no further issue description.
Please create a new one, if you need help.
All the best learning Android.
