### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by folsze** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#36]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#3
**Describe the problem**

Wrong, incosistency?
![image](https://user-images.githubusercontent.com/81622754/205966254-c8333f38-d778-42fd-86f8-b2d1e5b602c5.png)

**Comment by osuleymanova** [comment]
Hello @folsze,

Thank you for reaching out to us and bringing this inconsistency to our attention. The code snippets are updated:

![Screenshot 2023-01-11 at 4 21 55 PM](https://user-images.githubusercontent.com/86437155/211947081-ee16fdcf-67ef-42a2-b8ef-083b0bd80d3f.png)
