### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by sampotter123** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#37]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#7)

**In which task and step of the codelab can this issue be found?**

compile error ----- Type 'MutableState<Int>' has no method 'setValue(Nothing?, KProperty<*>, Int)' and thus it cannot serve as a delegate for var (read-write property)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by sc-gds-lxl** [comment]
This is addressed in the note:
```Note: The import androidx.compose.runtime.mutableStateOf and import androidx.compose.runtime.remember statements import the packages needed for the mutableStateOf function and the remember composable.

The following import statements are also needed to import necessary extension functions of State:

import androidx.compose.runtime.getValue

import androidx.compose.runtime.setValue```
