### ISSUE TITLE
Use function types and lambda expressions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by dcharlan426** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#39]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda#3

**In which task and step of the codelab can this issue be found?**
Nullable function types, step 3

**Describe the problem**
the lambda is replaced with null, but the code path executed never touches the lambda provided because the change is made when `isTrick` has a true value. If instead `coins` is replaced by null the check for `if (extraTreat != null) {` will be executed because `isTrick` is false.

**Steps to reproduce?**
1. with this implementation of `trickOrTreat`
```
fun trickOrTreat(isTrick: Boolean, extraTreat: ((Int) -> String)?): () -> Unit {
    if (isTrick) {
        return trick
    } else {
        if (extraTreat != null) {
            println(extraTreat(5))
        }
        return treat
    }
}
```
2. the main function should containing something like:
```
    val treatFunction = trickOrTreat(false, null)
    val trickFunction = trickOrTreat(true, cupcake)
```

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by dcharlan426** [comment]
This change will apparently ripple in to the next task - unfortunate

**Comment by johnshea** [comment]
Hi @dcharlan426 

Thanks for reaching out to us and sharing your feedback with us - it will be passed to the appropriate team for further consideration.

I hope you are enjoying the course.

Regards.
