### ISSUE TITLE
Write conditionals in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by visikoW** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#40]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals?hl=pt&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Dpt%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-conditionals#2

**In which task and step of the codelab can this issue be found?**
At the 

**Describe the problem**

**Steps to reproduce?**
1. Go to Language -> Portuguese
2. Click on Usar uma instrução when para várias ramificações
3. See error no sétimo ponto, onde fala sobre o else do when

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
[_Include screenshots if they would be useful in clarifying the problem._](https://drive.google.com/file/d/1oOx0jxoVQ9eCJEOgMLDi9k_P6x7MElfN/view?usp=sharing)

**Comment by osuleymanova** [comment]
Hello @visikoW,

Thank you for reaching out to us. The issue is fixed and will be published soon.
