### ISSUE TITLE
Write conditionals in Kotlin: Android Basics in Compose

### ISSUE THREAD

**Issue by newpaper818** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#41]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals?hl=ko&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Dko%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-conditionals#2

**In which task and step of the codelab can this issue be found?**
println(&quot;x is a prime number between 1 and 10.&quot;) 줄은 사례 1로 주석을 답니다. in 1..10 -> println(&quot;x is a number between 1 and 10, but not a prime number.&quot;) 줄은 사례 2로 주석을 답니다. else -> println(&quot;x isn&#39;t a prime number between 1 and 10.&quot;) 줄은 사례 3으로 주석을 답니다. " class="l10n-absolute-url-src" l10n-attrs-original-order="alt,style,src,class" l10n-encrypted-style="Bfmtwp4MR0V5uTC1s3uklU8zz2uYoEmRhrQeP6/mnhY=" src="https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals/img/bde4eca467c105a2.png" style="width: 624.00px" />

**Describe the problem**
only text, can't see image

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @newpaper818,

Thank you for reaching out to us. This issue is fixed and will be published soon.
