### ISSUE TITLE
Practice problems Unit 2 Pathway 1: Android Basics with Compose

### ISSUE THREAD

**Issue by newpaper818** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#42]
A ---
name: Practice problems unit 2 pathway 1 issue template
about: Issue template for Unit 1 | Pathway 1 | Practice Problems
title: 'Practice problems Unit 2 Pathway 1: Android Basics with Compose'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-kotlin-fundamentals-practice-problems?hl=ko&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Dko%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-kotlin-fundamentals-practice-problems#3

**In which task and step of the codelab can this issue be found?**
println("$initialMeasurement degrees $initialUnit is $finalMeasurement degrees $finalTemperature.")

**Describe the problem**
println("$initialMeasurement degrees $initialUnit is $finalMeasurement degrees $finalTemperature.")
to
println("$initialMeasurement degrees $initialUnit is $finalMeasurement degrees $finalUnit.")

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @newpaper818,

Thank you for reaching out to us. The typo is fixed:

![Screenshot 2023-01-09 at 5 28 12 PM](https://user-images.githubusercontent.com/86437155/211441297-d8b9f43c-c8c2-4c29-b264-ddfb225d6080.png)
