### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by MikeDeignan** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#45]
**URL of codelab** https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app#3

**In which task and step of the codelab can this issue be found?** Add a Modifier

**Describe the problem** The @Preview is shown above the fun DiceWithButtonAndImage() and has a parameter. In the solution file, it is positioned above fun DiceRollApp(). Confusing.)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @MikeDeignan,

Thank you for reaching out to us and bringing this inconsistency to our attention. The code snippet is fixed:

![Screenshot 2023-01-11 at 4 30 10 PM](https://user-images.githubusercontent.com/86437155/211947603-d3e9d2f1-23e1-470d-958d-ec7c7d8fe2d6.png)
