### ISSUE TITLE
Write conditionals in Kotlin: Android Basics in Compose | Korean 

### ISSUE THREAD

**Issue by kooBH** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#46]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Dko%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-conditionals&hl=ko#2

**In which task and step of the codelab can this issue be found?**

한국어, Korean   

[3. Use a when statement for multiple branches](https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Dko%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-conditionals#2)

**Describe the problem**  

+ Issue
![image](https://user-images.githubusercontent.com/39723411/211438472-c77156f5-b46f-4e30-ba6c-086aac84be81.png)

+ Normal
![image](https://user-images.githubusercontent.com/39723411/211438497-6800dc91-6e17-4897-a25f-1d3a4761cd47.png)

**Steps to reproduce?**
1. Go to https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Dko%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-conditionals&hl=ko#2

**Comment by osuleymanova** [comment]
Hello @kooBH,

Thank you for reaching out to us and reporting this localization issue. It is fixed and will be published soon.
