### ISSUE TITLE
Use function types and lambda expressions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by sreedevnair** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#47]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda#3

**In which task and step of the codelab can this issue be found?**
On Step Number 4 | Use functions as a data type

**Describe the problem**
Each of the steps of this codelab is almost 20 minutes long according to the _mins remaining_ shown above, except for the Step 4. While doing the Step 4, 24 mins are remaining, and after finishing that and moving on to the Step 5, 23 mins are remaining. This might be a really small bug but I think it takes more than 1 minute to go through Step 4.

**Steps to reproduce?**
1. Go the [codelab](https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda#3)
2. Select Step 4 and check the time remaining
3. Now press Next
4. Check the time remaining for the Step 5

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/55118303/211840853-e9abe71c-b8ff-42d0-874b-5046a69276b4.png)

![image](https://user-images.githubusercontent.com/55118303/211840994-678d77ba-c8c9-416c-bb0c-cef661c53f6d.png)

**Comment by osuleymanova** [comment]
Hello @sreedevnair,

Thank you for reaching out to us and sharing your concern regarding the durations. Throughout the course, you find durations for how long a part of the course/codelab/steps can potentially take. Note that these are estimates, and the actual amount of time you spend on it can vary widely for each person. But we got your point of view that 1 minute is not enough to go through all those steps, so we took an action to update the duration for the codelab mentioned:

![Screenshot 2023-01-12 at 9 42 31 AM](https://user-images.githubusercontent.com/86437155/212152917-4e01ff12-5a55-4a5d-9de5-cb1b3d81cdd0.png)
