### ISSUE TITLE
Practice problems Unit 2 Pathway 1: Android Basics with Compose

### ISSUE THREAD

**Issue by jensmoths** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#5]
A ---
name: Practice problems unit 2 pathway 1 issue template
about: Issue template for Unit 1 | Pathway 1 | Practice Problems
title: 'Practice problems Unit 2 Pathway 1: Android Basics with Compose'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-kotlin-fundamentals-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-kotlin-fundamentals-practice-problems#8

**In which task and step of the codelab can this issue be found?**
Step 9

**Describe the problem**
There is a typo on line 11 in the Mobile notifications solution code. noOfMessages should be numberOfMessages.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@jensmoths 
Thank you for reaching out to us. The typo is fixed and will be published soon:

![Screen Shot 2022-06-22 at 2 34 20 PM](https://user-images.githubusercontent.com/86437155/175142818-ebdd36fd-e0df-49a2-82d0-ad495c3dd377.png)
