### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by hhariri** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#52]
[**URL of codelab**
](https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#5)

**In which task and step of the codelab can this issue be found?**

6

**Describe the problem**

You have a commented out TODO which is assumed is the Kotlin TODO function which throws an exception. As a consequence, the rendering doesn't work.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @hhariri.

Thank you for letting us know of your issue.

I tried recreating your issue using the latest Android Studio and libraries but was unable. My code was rendering correctly in the **Design** pane and the emulator and was not throwing an exception.

So I can troubleshoot further, please attach the following...
- Full MainActivity.kt file
- A screenshot of the error(s)

If you are so inclined, please attach your zipped project so I can run your work locally.

Thank you in advance for your help.

Regards.

**Comment by hhariri** [comment]
@johnshea It's with 

Android Studio Electric Eel | 2022.1.1
Build #AI-221.6008.13.2211.9477386, built on January 11, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
[test.zip](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/files/10549393/test.zip)

Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.experimental.ui=true

But something is flaky cause it seems removing it also fails. 


I just added the TODO again and it fails to render. Attached is the project.

**Comment by johnshea** [comment]
Hi @hhariri.

Thank you for attaching your project.

Multiple team members tried running your project on Android Studio Electric Eel but unfortunately none of us were able to reproduce the error.

It sounds like it might be an issue with the Preview in Android Studio.

If you can see a stack trace in Android Studio, can you can report it through the IDE or through https://developer.android.com/studio/report-bugs?

To help confirm it is just a Preview issue, even though the Preview is not rendering can you try installing your app on an emulator or device to see if it renders as expected?

Can you also attach screenshots of the errors/exceptions you are seeing if possible?

If you are so inclined, try creating a new project using the "Empty Compose Activity" template (Not the "Empty Compose Activity (Material3)" template), build, and run it without making any changes to confirm that the Preview is rendering correctly.

Thanks you in advance for your troubleshooting help with this issue.

Regards.

**Comment by hhariri** [comment]
@johnshea If nobody can reproduce it, maybe then it's just something on my machine. I'll try and follow the exact steps I did with the tutorial from scratch once again and see if it happens. Unfortunately I don't have the time right now to do this. As such, please feel free to close the issue. If it happens again I'll comment on it. Apologies.

**Comment by johnshea** [comment]
Hi @hhariri.

Thank you for the update.

Time permitting, please give it another go but understand that it is not a priority.

I will close the issue for now but please reopen if necessary.

Hope you are enjoying the course!

Regards.
