### ISSUE TITLE
Write conditionals in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by A-zouine** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#53]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @A-zouine 

I will be closing this issue as no details were provided.

If you are still having an issue, please create a new issue with the required details so it can be addressed.

Hope you are enjoying the course!

Regards.
