### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by croworc** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#54]
**Type of issue**
Wrong/misleading explanation for correct instruction.

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app

**In which task and step of the codelab can this issue be found?**
Task: `5. Create a vertical layout`
Step: `Pass a horizontalAlignment parameter to the Column() function and then set it to an Alignment.CenterHorizontally value.`

**Describe the problem**
The explanation for this step's instruction (mentioned above) states:
`This ensures that the column is centered on the device screen with respect to the width.`

This, however, is not quite what the column's `horizontalAlignment` parameter actually does here, so maybe change to:
`This ensures that the column's children are centered horizontally within the column (which, itself, is already centered horizontally and vertically on the screen).`

Cheers! 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by sc-gds-lxl** [comment]
Resolved
