### ISSUE TITLE
Use nullability with Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by appsparkler** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#59]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-nullability?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-nullability#2

**In which task and step of the codelab can this issue be found?**
android-basics-compose-unit-2-pathway > basic-android-kotlin-compose-nullability > Step 3

**Describe the problem**
val is used instead of var

Actual:
```kt
fun main() {
    val favoriteActor: String? = "Sandra Oh"

    val lengthOfName = if (favoriteActor != null) {
      favoriteActor.length
    } else {
      
    }
}
```

Expected:
```kt
fun main() {
    var favoriteActor: String? = "Sandra Oh"

    val lengthOfName = if (favoriteActor != null) {
      favoriteActor.length
    } else {
      0
    }
}
```

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @appsparkler,

Thank you for reaching out to us. The typo is fixed and will be published soon.
