### ISSUE TITLE
Use function types and lambda expressions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by appsparkler** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#60]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda#4

**In which task and step of the codelab can this issue be found?**
5th step of [Use function types and lambda expressions in Kotlin](https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda)

**Describe the problem**

`quantity` variable is missing

Actual:
```kt
val coins: (Int) -> String = {
    "$quantity quarters"
}
```

Expected:
```kt
val coins: (Int) -> String = {
   quantity ->  "$quantity quarters"
}
```

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @appsparkler.

Thank you for writing in with your concern.

The 5th step is having the student remove `quantity ->` and change the variable name to `it`.

From how I read your concern, I do not believe you are completing all the steps in the lesson as your code does not contain `it` as instructed.

If I am misunderstanding, please open a new issue with additional information so we can investigate this further.

Hope you are enjoying the course.

Regareds.
