### ISSUE TITLE
Write conditionals in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by daniel-kuak** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#61]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals?hl=ko&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Dko%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-conditionals#2

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
I can see the html tags in the context only in Korean.
![Screenshot_20230329_091444_Chrome](https://user-images.githubusercontent.com/19297866/228394576-7949e2e3-1028-4ea8-86fd-3da60f10a476.jpg)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @daniel-kuak,

Thank you for reaching out and reporting this issue. Unfortunately, the images are not rendered correctly in Korean language, so the issue will be assigned and handled by localization team.

**Comment by johnshea** [comment]
Hi @daniel-kuak 

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
