### ISSUE TITLE
Use nullability with Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by daniel-kuak** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#62]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
There is no . Operator instruction before this page
![Screenshot_20230329_092624_Chrome](https://user-images.githubusercontent.com/19297866/228395820-e88d0993-9a17-40b3-922e-25624d4e0a03.jpg)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @daniel-kuak 

Thank you for writing in with this issue.

While we did use them in [Unit 1 Pathway 2](https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app) it is possible that it could have been clearer.

I will pass along your feedback to the appropriate team so they can review and address as needed.

Hope you are enjoying the course!

Regards.
