### ISSUE TITLE
Use function types and lambda expressions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by vinaysharma1987** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#63]
Minor issue in pictorial representation of concept 
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda#4

**In which task and step of the codelab can this issue be found?**
[Use function types and lambda expressions in Kotlin](https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda)
![image](https://user-images.githubusercontent.com/10243305/230909339-8dbf33ce-dc3c-4d28-8d09-d02a0689ece0.png)

**Describe the problem**

In this case, there will be a single parameter as per the example and concept. It should be something like the following:
![image](https://user-images.githubusercontent.com/10243305/230909544-0b88914b-3cab-4fca-8d4e-84edea34e533.png)

or may be something like this 
![image](https://user-images.githubusercontent.com/10243305/230911544-e74b7474-9b02-44c0-9500-00081cc9c70d.png)
Its creating doubt for students. 
even heading also needs to change  : Omit parameter names
to : Omit parameter name

**Steps to reproduce?**
1. Go to... [Use function types and lambda expressions in Kotlin](https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda)

3. See error in first image

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @vinaysharma1987 

Thank you for writing in to bring this issue to our attention and also for providing some suggested ways to address it.

The codelab image has been updated and the codelab itself will be republished in the near future.

Hope you are enjoying the course!

Regards.
