### ISSUE TITLE
Use function types and lambda expressions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by bunnycou** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#65]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda#3

**In which task and step of the codelab can this issue be found?**
Task 4 Step 5

**Describe the problem**

> Note: In the coins() function, the Int parameter is named quantity. However, it could be named anything or even omitted entirely as is done with the cupcake() function.

The `quantity ->` cannot be omitted from coins() without also omitting the reference in the string, but if you do that then this serves no purpose and pointing this out is a waste.

**Comment by bunnycou** [comment]
To further elaborate, since it can be omitted and replaced with `it`, it isn't _wrong_ but since that is explained in the next task it isn't worth half explaining it there and should be removed

**Comment by johnshea** [comment]
Hi @bunnycou 

Thank you for writing in and providing this valuable feedback.

The lesson wording has been updated and the lesson will be republished in the near future.

Hope you are enjoying the course!

Regards.
