### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose here i am not able download images because the site cannot be reached

### ISSUE THREAD

**Issue by ShriramBM** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#68]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @ShriramBM 

Thank you for writing in with your issue.

I can confirm that that site is working and I can download the image resources.

It is a known issue that some in some parts of the world that GitHub access is blocked for downloading of resources. This might be what you are experiencing.

If you do not feel this applies to your situation, please open a new issue and provided further details so it can be further investigated.

Hope you are enjoying the course.

Regards.
