### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by BriannaMaria** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#69]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#4

**In which task and step of the codelab can this issue be found?**
"The import statement for the Button composable is import androidx.compose.material3.Button."

**Describe the problem**
I think the right import is: import androidx.compose.material.Button, without the "3"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @BriannaMaria.

Thank you for writing in with your issue.

I would recommend checking, and possibly updating, your version of Android Studio to the latest stable version.

The lessons have been updated for Material 3 and it is possible you are using an older version that uses the Material 2 template causing this discrepancy you are experiencing.

If you are still having an issue, please do not hesitate to open a new issue with the required information concerning steps to reproduce, versions, etc.

Hope you are enjoying the course.

Regards.
