### ISSUE TITLE
Art Space app: Android Basics in Compose----------------HELP WITH PUTTING BUTTON IN CORRECT SPOT

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#7]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**1. I have the button on the app  main screen but for some reason, it is UNDERNEATH the 1st piece of artwork.  I want it to be underneath,  Year: 2022.         Do I have my button code in the wrong spot?       Where does it go, because I tried everything.*. 

2 screen shots below
<img width="1440" alt="Screen Shot 2022-07-08 at 2 04 14 PM" src="https://user-images.githubusercontent.com/91148652/178055364-e67ea61d-f3bb-4b4b-9bb4-750598e4d639.png">

<img width="1440" alt="Screen Shot 2022-07-08 at 2 04 30 PM" src="https://user-images.githubusercontent.com/91148652/178055369-248bbd3a-f59a-4297-b47b-d2ddc89ca730.png">
    
**Describe the problem**

**Steps to reproduce?**
1. Go to...
3. Click on...
4. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by YaerQ** [comment]
It's because you have them on the @Preview composable.
the Preview @Composable should look like this:

```
@Preview(showBackground = true)
@Composable
fun ArtSpaceAppPreview() {
    ArtSpaceAppTheme {
        ArtSpaceApp()
    }
}
```

"ArtSpaceApp" is the name I gave to the main composable function, the one that will hold all the ui elements (yours can be called different) You shouldn't write code in there other than calling the main composable

 Also you don't need to create a Button @Composable function. to create a button there is a built in composable made for you Ex.  

```
Button(onClick = { /*TODO*/ }, modifier = Modifier.width(100.dp)) {
                Text(text = "Previous")
            }

Button(onClick = { /*TODO*/ }, modifier = Modifier.width(100.dp)) {
                Text(text = "Next")
            }
```
In that button code I added the Modifier.width so the buttons are the same width, if you leave it default it will wrap around the text so the "Next" button will look narrower.
You use them the same as the Column and Row composables. I'm doing this codelab too so I'm still learning like yourself, but let me know if you want to check my code. 
This is my result so far: 
  
![codelab](https://user-images.githubusercontent.com/107282813/178113686-369528de-e8c5-4ee5-9a8c-56ee17a7616d.jpg)

**Comment by jh115424** [comment]
gee thanks for the fast answer!   I will do some experimenting and try this!

I will let you know how things go, and if I discover anything that works also, I will share with you!  🙂


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:eb809446-42a8-4e9a-8df1-592840e8cdd6]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
so are you saying that this code should be deleted out the @preview, @Compasable, fun ArtSpaceAppPreview?

<img width="1440" alt="Screen Shot 2022-07-09 at 11 51 09 AM" src="https://user-images.githubusercontent.com/91148652/178115313-72e00e50-211f-40f7-952f-fa399aeb8ca2.png">

**Comment by jh115424** [comment]
I sent you a reply in GitHub


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:3b085a19-e785-4fbf-aaf6-577b248b3d05]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
Is it possible if I can see your code, just so I can get unstuck?

Please?


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:afb22814-3fd1-4546-b96d-98e848ac5bee]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by YaerQ** [comment]
Sure but keep in mind it's not finished and I'm still tinkering with it.

**Comment by YaerQ** [comment]
```
package com.example.artspaceapp

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.Image
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.Button
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Surface
import androidx.compose.material.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.RectangleShape
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.artspaceapp.ui.theme.ArtSpaceAppTheme

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            ArtSpaceAppTheme {
                // A surface container using the 'background' color from the theme
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colors.background
                ) {
                    ArtSpaceApp()
                }
            }
        }
    }
}

@Composable
fun ArtSpaceApp() {
    Column(
        modifier = Modifier
            .fillMaxHeight()
            .padding(start = 16.dp, end = 16.dp)
    ) {
        var currentView by remember { mutableStateOf(1) }

        ArtistCard(
            artworkTitle = "Something Something",
            artworkArtist = "Famous Artist",
            artworkYear = "(2008)",
            imageResourceId = R.drawable.image5,
            imageDescriptionTextId = R.string.app_name
        )

    }
}

@Composable
fun ArtistCard(
    artworkTitle: String,
    artworkArtist: String,
    artworkYear: String,
    imageResourceId: Int,
    imageDescriptionTextId: Int
) {

    val artistFontSize = 14.sp

    Column(
        modifier = Modifier.fillMaxSize(),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.SpaceBetween

    ) {
//Image Surface
        Surface(
            border = BorderStroke(2.dp, Color.Black),
            shape = RectangleShape,
            elevation = 4.dp,
            modifier = Modifier
                .wrapContentSize()
                .weight(7f)
                .padding(top = 30.dp)
        )
        {
            Image(
                painter = painterResource(imageResourceId),
                contentDescription = stringResource(imageDescriptionTextId),
                contentScale = ContentScale.FillWidth,
                modifier = Modifier
                    .padding(36.dp)
                    .fillMaxWidth()
            )

        }
// Artist Info Surface
        Surface(
            shape = RectangleShape,
            elevation = 4.dp,
            modifier = Modifier
                .weight(1f)
                .wrapContentSize()
        ) {

            Column(
                horizontalAlignment = Alignment.Start,
                modifier = Modifier

                    .padding(16.dp)
            )
//Art Name
            {
                Text(
                    text = artworkTitle,
                    fontSize = 24.sp,
                    textAlign = TextAlign.Start

                )
//Artist Name and Art Date
                Row(
                    horizontalArrangement = Arrangement.SpaceEvenly
                ) {
                    Text(
                        text = artworkArtist,
                        fontSize = artistFontSize,
                        fontWeight = FontWeight.Bold,
                        modifier = Modifier.padding(end = 4.dp)
                    )
                    Text(text = artworkYear, fontSize = artistFontSize)
                }

            }

        }
        Row(
            horizontalArrangement = Arrangement.SpaceEvenly,
            verticalAlignment = Alignment.CenterVertically,
            modifier = Modifier
                .fillMaxWidth()
                .weight(1f)
        )
        {
            Button(onClick = { /*TODO*/ }, modifier = Modifier.width(100.dp)) {
                Text(text = "Previous")
            }
            Button(onClick = { /*TODO*/ }, modifier = Modifier.width(100.dp)) {
                Text(text = "Next")
            }
        }
    }


}


@Preview(showBackground = true)
@Composable
fun ArtSpaceAppPreview() {
    ArtSpaceAppTheme {
        ArtSpaceApp()
    }
}

```

**Comment by jh115424** [comment]
thats fine....just a rough guide just so I can kind of compare.

Now what code would I use to click to the next art piece and would I put each piece physically on the screen under my first one, or no?


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:b628e380-eb6a-42e0-9735-791f2451dd40]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by YaerQ** [comment]
> thats fine....just a rough guide just so I can kind of compare. Now what code would I use to click to the next art piece and would I put each piece physically on the screen under my first one, or no? Jennifer Hodge Internet Sales 414-586-5425 Russ Darrow Honda [cid:b628e380-eb6a-42e0-9735-791f2451dd40]<https://your.tradeinvalet.com/tdhe0j>
> […](#)

I haven't arrive at that part yet, this code is still all UI there is no button functionality yet. So I have to figure that out.

**Comment by jh115424** [comment]
well, at least we are both at the same page!   We will help each other when one of us gets a breakthrough on that!  lol

sound good?


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:12b97b0d-5cfe-46e3-afef-5d14eb03a822]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by YaerQ** [comment]
> well, at least we are both at the same page! We will help each other when one of us gets a breakthrough on that! lol sound good? Jennifer Hodge Internet Sales 414-586-5425 Russ Darrow Honda [cid:12b97b0d-5cfe-46e3-afef-5d14eb03a822]<https://your.tradeinvalet.com/tdhe0j>
> […](#)
Sure :)

**Comment by jh115424** [comment]
I sent one more question in Github about Toast.


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:ed728ef7-4e1c-4b8d-bedd-71001d276090]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
Great news friend!   I figured out so far how to add the next art piece under the first one.....just now!

See Github for the screenshots! and code!  🙂


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:dd08e44f-3b99-45c8-a8ba-7d087c02d012]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
Here is a way I just found to add the next art piece under the 1st piece!

See the screenshot below!      Now getting the button to click to the 2nd one......work in progress, unless you found a way?


<img width="1440" alt="Screen Shot 2022-07-10 at 7 46 28 AM" src="https://user-images.githubusercontent.com/91148652/178145507-f9828a48-572e-4254-8cdf-95dab9d0803a.png">

**Comment by YaerQ** [comment]
Yes I found a way, you have to make the the button trigger a recompose to display the next art piece. you can do that with `var artPiece by remember {mutableStateOf(1)}`. What that does is that when the app recomposes the UI it remembers the value given in mutableStateOf() even when it changes which in this case is 1. You can then have a `when` expression that depending on the value of the artPiece variable it will show a different composable. And you trigger that variable change with the button.

**Comment by YaerQ** [comment]
Also I see that you made a composable for each piece of art, that will work but let say that you have 50 art pieces, making a unique composable for each is too much work. So try to make your art piece composable reusable.

**Comment by jh115424** [comment]
How do I do that?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jh115424** [comment]
Is that in the code you sent me on the weekend?

If not, what does that look like?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jh115424** [comment]
Nevermind.....I see it in the code u sent.

Disregard.

Thx

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by YaerQ** [comment]
That code is outdated. This one is recent:

```
package com.example.artspaceapp

import android.os.Bundle

import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.*
import androidx.compose.material.Button
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Surface
import androidx.compose.material.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.RectangleShape
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.artspaceapp.ui.theme.ArtSpaceAppTheme

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            ArtSpaceAppTheme {
                // A surface container using the 'background' color from the theme
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colors.background
                ) {
                    ArtSpaceApp()
                }
            }
        }
    }
}

@Composable
fun ArtSpaceApp() {
    Column(
        modifier = Modifier
            .fillMaxHeight()
            .padding(start = 16.dp, end = 16.dp)
    ) {
        var currentImage by remember {mutableStateOf(1)}

        when (currentImage) {

            1 -> {
                ArtWithArtistCard(
                    artworkTitle = "Too Many Leaves on My Face",
                    artworkArtist = "Leavy Forrest",
                    artworkYear = "(2008)",
                    imageResourceId = R.drawable.image1,
                    imageDescriptionTextId = R.string.app_name,
                    onNextClick = {currentImage = 2},
                    onPreviousClick = {currentImage = 5}
                )
            }

            2 -> {
                ArtWithArtistCard(
                    artworkTitle = "Kitty Cat",
                    artworkArtist = "Kat Jennings",
                    artworkYear = "(2018)",
                    imageResourceId = R.drawable.image2,
                    imageDescriptionTextId = R.string.app_name,
                    onNextClick = {currentImage = 3},
                    onPreviousClick = {currentImage = 1}
                )
            }

            3 -> {
                ArtWithArtistCard(
                    artworkTitle = "Are Fish Real?",
                    artworkArtist = "Sean Tunalo",
                    artworkYear = "(2020)",
                    imageResourceId = R.drawable.image3,
                    imageDescriptionTextId = R.string.app_name,
                    onNextClick = {currentImage = 4},
                    onPreviousClick = {currentImage = 2}
                )
            }

            4 -> {
                ArtWithArtistCard(
                    artworkTitle = "Ruining Mom's Garden",
                    artworkArtist = "Potter Green",
                    artworkYear = "(2019)",
                    imageResourceId = R.drawable.image4,
                    imageDescriptionTextId = R.string.app_name,
                    onNextClick = {currentImage = 5},
                    onPreviousClick = {currentImage = 3}
                )
            }

            5 -> {
                ArtWithArtistCard(
                    artworkTitle = "It's not Even Raining",
                    artworkArtist = "Rihanna",
                    artworkYear = "(2010)",
                    imageResourceId = R.drawable.image5,
                    imageDescriptionTextId = R.string.app_name,
                    onNextClick = {currentImage = 1},
                    onPreviousClick = {currentImage = 4}
                )
            }
        }



    }
}

@Composable
fun ArtWithArtistCard(
    artworkTitle: String,
    artworkArtist: String,
    artworkYear: String,
    imageResourceId: Int,
    imageDescriptionTextId: Int,
    onNextClick: () -> Unit,
    onPreviousClick: () -> Unit,
) {

    val artistFontSize = 14.sp

    Column(
        modifier = Modifier.fillMaxSize(),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.SpaceBetween

    ) {
//Image Surface
        Surface(
            border = BorderStroke(2.dp, Color.Black),
            shape = RectangleShape,
            elevation = 4.dp,
            modifier = Modifier
                .wrapContentSize()
                .weight(7f)
                .padding(top = 30.dp)
        )
        {
            Image(
                painter = painterResource(imageResourceId),
                contentDescription = stringResource(imageDescriptionTextId),
                contentScale = ContentScale.FillWidth,
                modifier = Modifier
                    .padding(36.dp)
                    .fillMaxWidth()
            )

        }
// Artist Info Surface
        Surface(
            shape = RectangleShape,
            elevation = 4.dp,
            modifier = Modifier
                .weight(1f)
                .wrapContentSize()
        ) {

            Column(
                horizontalAlignment = Alignment.Start,
                modifier = Modifier
                    .padding(16.dp)
            ) {
                Text(
                    text = artworkTitle,
                    fontSize = 24.sp,
                    textAlign = TextAlign.Start

                )
//Artist Name and Art Date
                Row(
                    horizontalArrangement = Arrangement.SpaceEvenly
                ) {
                    Text(
                        text = artworkArtist,
                        fontSize = artistFontSize,
                        fontWeight = FontWeight.Bold,
                        modifier = Modifier.padding(end = 4.dp)
                    )
                    Text(text = artworkYear, fontSize = artistFontSize)
                }
            }
        }
        Row(
            horizontalArrangement = Arrangement.SpaceEvenly,
            verticalAlignment = Alignment.CenterVertically,
            modifier = Modifier
                .fillMaxWidth()
                .weight(1f)
        ) {
            Button(onClick = {onPreviousClick()}, modifier = Modifier.width(100.dp)) {
                Text(text = "Previous")
            }
            Button(onClick = {onNextClick()}, modifier = Modifier.width(100.dp)) {
                Text(text = "Next")
            }

        }
    }
}


@Preview(showBackground = true)
@Composable
fun ArtSpaceAppPreview() {
    ArtSpaceAppTheme {
        ArtSpaceApp()
    }
}
```

**Comment by jh115424** [comment]
how do you try to make a composable reusable?   I never heard that.

**Comment by YaerQ** [comment]
State Hoisting,  if you check the code I sent the ArtWithArtistCard composable you can see I gave it a bunch of properties
```
@Composable
fun ArtWithArtistCard(
    artworkTitle: String,
    artworkArtist: String,
    artworkYear: String,
    imageResourceId: Int,
    imageDescriptionTextId: Int,
    onNextClick: () -> Unit,
    onPreviousClick: () -> Unit,
) {

```
 (the code between the parenthesis after the composable name) when you do that you can call those in place of hardcoding the images, texts, other code and even other composables. 

for example if you check in the code were I add the image: 
```
Image(
                painter = painterResource(imageResourceId),
                contentDescription = stringResource(imageDescriptionTextId),
                contentScale = ContentScale.FillWidth,
                modifier = Modifier
                    .padding(36.dp)
                    .fillMaxWidth()
            )

```
In the painterResource I called the imageReasouceId propterty I made instead of hard coding an image file directly. I did the same with the text section and on the button onclick. If you do that you can use the same composable over and over as you can see on the `when` section of the code. I used the same composable but changed the values of each properties. 

I'm probably not explaining this correctly but if you check the code it should make sense.

**Comment by jh115424** [comment]
Ooooohhh...I see....that does make sense.   I'll have to practice that on a separate compose template to get the hang of it, so I don't mess up what I did so far on my project!  Lol

Thx again!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
