### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by Jawmt** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#70]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#1

**In which task and step of the codelab can this issue be found?**

[2. Establish a baseline]

**Describe the problem**

Create Project :

2 - I think It's : Create Empty Compose Activity and not Create Empty Activity

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Jawmt 

Thank you for writing in with your issue.

It later versions of Android Studio it changes from "Create Empty Compose Activity" to "Create Empty Activity". This can be seen in the lesson's screenshot of this step.

Hope you are enjoying the course.

Regards.
