### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by EzeGmnz** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#71]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#5)

**In which task and step of the codelab can this issue be found?**
Step 6

**Describe the problem**
This note should refer to the `Image` composable import (which hasn't been explained yet), since the `Column` Composable import package has  already been explained in previous steps
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/assets/40328394/0a1d6d6c-5afb-40cd-b811-09a887285bd9)

**Comment by johnshea** [comment]
Hi @EzeGmnz 

Thank you for writing in and bringing this issue to our attention.

The lesson has been updated to show the import statement for the Image composable as you correctly pointed out.

The lesson with the update will be republished in the near future.

Hope you are enjoying the course!

Regards.
