### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by Geek-Joe** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#72]
**URL of codelab**
https://developer.android.google.cn/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.google.cn%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#2

**In which task and step of the codelab can this issue be found?**
the last code snippet:
```
fun DiceWithButtonAndImage(modifier = Modifier
    .fillMaxSize()
    .wrapContentSize(Alignment.Center)
)
```

**Describe the problem**

1. the type(Modifier) of the parameter(modifier) is missing.
2. the keyword **fun** for composable function **DiceWithButtonAndImage** is missing from the penultimate 3 code snippets

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Geek-Joe.

Thank you for writing in with your concern.

I reviewed the code in question and it is correct. The two items you noted in "Describe the problem" are not needed.

The content at this point of the lesson is detailing how you call the function and what is passed so the keyword `fun` nor the type `Modifier` are  needed.

This code is not a continuation of the function definition shown in previous steps.

If I am misunderstanding, please do not hesitate to open a new issue with further details.

Regards.
