### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by imhjz** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#75]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?hl=zh-cn&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%3Fhl%3Dzh-cn%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#3

**In which task and step of the codelab can this issue be found?**
Step 4, last 3 code boxs

**Describe the problem**
wrong codes in the code boxs:
DiceWithButtonAndImage(modifier = Modifier)

correct codes:
DiceWithButtonAndImage(modifier: Modifier= Modifier)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @imhjz 

Thank you for writing in with your issue.

The last three code boxes are written correctly and do not need the `: Modifier` as you noted.

The last three are calling the function. The previous one was defining the function.

Hope you are enjoying the course.

Regards.
