### ISSUE TITLE
Use function types and lambda expressions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Alottachairs** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#76]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda&hl=en#1

**In which task and step of the codelab can this issue be found?**

Typo in directions

**Describe the problem**

"It's recommended to expand the video to full screen (with this icon This symbol shows 4 corners on a square highlighted, to indicate full screen mode. in the lower right corner of the video) so you can see Android Studio and the code more clearly."

- Angie is using Kotlin playground to show the examples in the code lab. not Android Studio.

**Steps to reproduce?**
1. Go to...  URL,
2. Click on... Optional Video tab step
3. See error... Typo in description

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Alottachairs** [comment]
Typo fix, please update "Android Studio" to "Kotlin Playground".

**Comment by johnshea** [comment]
Hi @Alottachairs 

Thank you for bringing this issue to our attention.

It has been corrected and the updated lesson will be republished in the near future.

Hope you are enjoying the course!

Regards.

**Comment by Alottachairs** [comment]
Loving the course!

Thank you so much!
