### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by zamri98** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#77]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#6

**In which task and step of the codelab can this issue be found?**
7-Build the dice-roll logic

**Describe the problem**

the code of : var result by remember { mutableStateOf(1) } resulting an error of 

**Steps to reproduce?**
1. Go to...7-Build the dice-roll logic
2. Click on...or use the code of : var result by remember { mutableStateOf(1) }
3. See error...Type 'TypeVariable(T)' has no method 'getValue(Nothing?, KProperty<*>)' and thus it cannot serve as a delegate and Variable expected

**Versions**
_Android Studio version:_ 2022.2.1 Patch 2
_API version of the emulator:_ API 33

**Solutions**
i replace the problem code with this     

var rollResult = remember {
        mutableStateOf(1)
    }

it work and the project was able to run as intended

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @zamri98 

Thank you for writing in with your issue.

In the lesson, directly following this line of code is a "Note" box that explains the imports needed to resolve this issue.

Please follow these steps to see if this resolves it for you.

If you still experiencing it, please do not hesitate to create a new issue.

Hope you are enjoying the course!

Regards.
