### ISSUE TITLE
Write conditionals in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Duck-jun99** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#79]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Dko#2

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
When setting the language in Korean from the above URL, the part "The output is a slow message because:" does not come out properly. Other parts have the same problem.

**Steps to reproduce?**
1. Go to... Above URL
2. Click on... Language(Korean)
3. See error... 

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Duck-jun99 

Thank you for writing in and bringing this to our attention.

It has been reported to our localization team so it can be addressed.

Hope you are enjoying the course!

Regards.
