### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by steventran619** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#80]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#5

**In which task and step of the codelab can this issue be found?**
Add a button to an app
Step 2 -  Create an interactive Dice Roller app

**Describe the problem**
`Note: The import statement for the Column composable is import androidx.compose.foundation.layout.Column.`

The note above is mentioned after adding the `Image` composable. The import statement is for the `Column` composable instead of the `Image` composable. Should provide the import statement for the `Image` composable. The `Column` import statement should be mentioned instead in [Step 4 - Create a vertical layout](https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#3) where its introduced.

**Steps to reproduce?**
N/A

**Versions**
N/A

**Additional information**
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/assets/65416951/d823f54a-5bec-42b6-9372-3fbe9bb4a159)

**Comment by johnshea** [comment]
Hi @steventran619 

Thank you for bringing this to our attention.

The lesson has been updated to address this and will be republished again in the near future with the fixes.

Hope you are enjoying the course!

Regards.
