### ISSUE TITLE
Use function types and lambda expressions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by Nhutking21** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#85]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda#3

**In which task and step of the codelab can this issue be found?**
Pass a function to another function as an argument

**Describe the problem**
The result is not correct as described.

After run this code in Kotlink Playground:

fun main() {
    val coins: (Int) -> String = { quantity ->
        println("$quantity quarters")
    }
    
    val cupcake: (Int) -> String = {
    	println("Have a cupcake!")
    }
    
    val treatFunction = treatOrTrick(false, coins)
    val trickFunction = treatOrTrick(true, cupcake)
    
    treatFunction()
    trickFunction()
}

fun treatOrTrick(isTrick: Boolean, extraTreat: (Int) -> String): () -> Unit {
    if (isTrick) {
        return trick
    } else {
        println(extraTreat(5))
        return treat
    }
}

val trick = {
    println("No treats!")
}

val treat: () -> Unit = {
    println("Have a treat!")
}

The result is: Type mismatch: inferred type is Unit but String was expected

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Nhutking21** [comment]
> Hi @Nhutking21, before trying to address this issue, could you reformat the code in your comment to make it more readable? That will make it easier to try to reproduce the issue.

Ah sorry, the snippet code is:

```
fun main() {
    val coins: (Int) -> String = { quantity ->
        "$quantity quarters"
    }

    val cupcake: (Int) -> String = {
        "Have a cupcake!"
    }

    val treatFunction = trickOrTreat(false)
    val trickFunction = trickOrTreat(true)
    treatFunction()
    trickFunction()
}

fun trickOrTreat(isTrick: Boolean, extraTreat: (Int) -> String): () -> Unit {
    if (isTrick) {
        return trick
    } else {
        println(extraTreat(5))
        return treat
    }
}

val trick = {
      println("No treats!")
}

val treat: () -> Unit = {
     println("Have a treat!")
}

```
The result is: Type mismatch: inferred type is Unit but String was expected

**Comment by Nhutking21** [comment]
But today the Kotlin Playground produced the right answer for me. Don't know why.

Thanks.

**Comment by johnshea** [comment]
Hi @Nhutking21 

Thank you for writing in and also formatting your code.

The issue is because in your original code you had...
```
val cupcake: (Int) -> String = {
	println("Have a cupcake!")
}
```

But in your formatted code you had the following which is what the lessons instructs.
```
    val cupcake: (Int) -> String = {
        "Have a cupcake!"
    }
```

You should not have had the `println` statement.

Hope you are enjoying the course!

Regards.
