### ISSUE TITLE
Basic android | Kotlin Compose | Practice Problems #7

### ISSUE THREAD

**Issue by RicardoMeloDaRocha** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#87]
A ---
name: 
about: Basic android | Kotlin Compose | Practice Problems #7
title: 'special auction'
labels: ''
assignees: ''

---

**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-kotlin-fundamentals-practice-problems?hl=pt-br&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fhl%3Dpt-br%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-kotlin-fundamentals-practice-problems#7

**In which task and step of the codelab can this issue be found?**

Problem #7

**Describe the problem**

This code dont work for “Private Collector”=6000

fun main() {
    val winningBid = Bid(5000, "Private Collector")

    println("Item A is sold at ${auctionPrice(winningBid, 2000)}.")
    println("Item B is sold at ${auctionPrice(null, 3000)}.")
}

class Bid(val amount: Int, val bidder: String)

fun auctionPrice(bid: Bid?, minimumPrice: Int): Int {
    if (bid!=null){
        if(bid.amount<minimumPrice){
           return minimumPrice
        }else{
            return bid.amount
        }
    }else{
        return minimumPrice
    }
   
}

This code works for “Private Collector”=6000

fun main() {
    val winningBid = Bid(5000, "Private Collector")

    println("Item A is sold at ${auctionPrice(winningBid, 2000)}.")
    println("Item B is sold at ${auctionPrice(null, 3000)}.")
}

class Bid(val amount: Int, val bidder: String)

fun auctionPrice(bid: Bid?, minimumPrice: Int): Int {
    if (bid!=null){
        if(bid.amount<minimumPrice){
           return minimumPrice
        }else{
            return bid.amount
        }
    }else{
        return minimumPrice
    }
   }

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/assets/141185047/4dd99b7b-e772-4964-9f3f-7e2ed377f7f9)

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/assets/141185047/b4394032-ba88-43cf-99fe-f89382cfea3c)

**Comment by johnshea** [comment]
Hi @RicardoMeloDaRocha 

Thank you for writing in.

If there is a bidder, the item is sold for that amount even if it is less than the minimum price.

The minimum price is only used if there is no bidder.

Hope this helps clarify the issue.

Regards.
