### ISSUE TITLE
Practice problems Unit 2 Pathway 1: Android Basics with Compose: "degrees" Kelvin

### ISSUE THREAD

**Issue by LinuxBrickie** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#88]
A ---
name: Practice problems unit 2 pathway 1 issue template
about: Issue template for Unit 1 | Pathway 1 | Practice Problems
title: 'Practice problems Unit 2 Pathway 1: Android Basics with Compose'
labels: ''
assignees: ''

---

**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-kotlin-fundamentals-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-kotlin-fundamentals-practice-problems#3

**In which task and step of the codelab can this issue be found?**

4. Temperature converter

**Describe the problem**

It is a common mistake/misconception but there is no such thing as "degrees" Kelvin. The unit is simply Kelvin.

It might be an idea to alter the exercise to take account of this difference between Kelvin and the other two units (after all it's only an if statement away which is covered by the previous exercises).

**Steps to reproduce?**

N/A

**Versions**

N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @LinuxBrickie 

Thank you for bringing this our attention.

I will share it with team so they can decide how they want to address it in the practice problem.

Hope you are enjoying the course!

Regards.
