### ISSUE TITLE
Use function types and lambda expressions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by hassan0599** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#89]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda#3

**In which task and step of the codelab can this issue be found?**
-> Task 4 (Use functions as a data type)
-> Nullable function types
-> Bullet point 1

**Describe the problem**
The step "Change the extraTreat parameter's type to (() -> String)?." should be excluded/deleted as it is incorrect.

**Comment by Bbarbe-CDS** [comment]
asasa

**Comment by johnshea** [comment]
Hi @hassan0599 

Thank you for writing in and sharing your concern.

I will it with the team so they can address it as needed.

Hope you are enjoying the course!

Regards.
