### ISSUE TITLE
Art Space app: Android Basics in Compose

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#9]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

Why does my makeText give a red line in the toast?    Sorry for all the questions.    This is the last one for a while!

<img width="1440" alt="Screen Shot 2022-07-09 at 2 22 57 PM" src="https://user-images.githubusercontent.com/91148652/178119931-c8c6c7e0-2cd4-4e5d-939d-de642feea21b.png">

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by YaerQ** [comment]
What does the error message say?

**Comment by jh115424** [comment]
None of the following functions can be called with the arguments supplied.

makeText(Context!, CharSequence!, Int) defined in android.widget.Toast
makeText(Context!, Int, Int) defined in android.widget.Toast


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:599b4539-9c22-4237-9083-38ad800a5c28]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by YaerQ** [comment]
try 

```
val context = LocalContext.current
            Button(onClick = { Toast.makeText(context,"Button Clicked", Toast.LENGTH_LONG).show()}) {
                
            }
```

**Comment by jh115424** [comment]
Ok, thanks!  I'll try it when I get to Starbucks early tomorrow morning at 6 and let u know! (I go every Wednesday and Sunday morning on my days off to practice😁



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jh115424** [comment]
well.....the code DID get rid of the red underline under makeText but it still wont make the button display the toast when I click on it.   Maybe it is something else I have to do.

hmmmmmm.........well.....the search is on!


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:43dfa5d0-215d-4404-84bc-022984691bd8]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by YaerQ** [comment]
I tried on my end and it worked. Make sure to replace  ` Toast.makeText(this,` with ` Toast.makeText(context,`

**Comment by jh115424** [comment]
Hmmmm...OK I'll double check.

I sent u an update in GitHub unless u already saw it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jh115424** [comment]
What kind of button code would i put in the Todo section, other than toast?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jh115424** [comment]
Yes!    The toast worked.     I uploaded on my phone.😁


Now do I use navigation code to get it to click from next to previous?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by YaerQ** [comment]
Now you have to program a way to recompose the UI with a different composition every time you click the button. But that's gonna depend on how you built your composables.

**Comment by jh115424** [comment]
Hi Yaer!

Well, I am finally finished with putting my 4 art pieces.....

I found a good combination of codes that work and load properly.

I uploaded both screen shots here, showing my 4 art pics, and I figured out the card view also.


If you cant see them here, look in Github in our chat.

Let me know if you want to see my code.

Now the grand finale......to add the buttons and get them to click to each image!

Since the screenshots are too big, I sent them in the next email!


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jh115424** [comment]
Hope you like the art I found!    It was during business trips to Chicago! Some at my hotel and some outside!

Yours is cool also!
😁

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by YaerQ** [comment]
> Hi Yaer! Well, I am finally finished with putting my 4 art pieces..... I found a good combination of codes that work and load properly. I uploaded both screen shots here, showing my 4 art pics, and I figured out the card view also. If you cant see them here, look in Github in our chat. Let me know if you want to see my code. Now the grand finale......to add the buttons and get them to click to each image! Since the screenshots are too big, I sent them in the next email! Get Outlook for Android<https://aka.ms/AAb9ysg>
> […](#)

Hi
That's awesome! Yeah that's the trick. There are so many ways to do things that you will always find a way that works for you, and as long as it loads without any error then its fine 😁.  Yes I wouldn't mind checking your code. The art you found looks great, mine are just random images from google since the app wouldn't be published lol. 

The buttons is the tricky part, like I mentioned earlier the easiest way is with a `when`  expression and a variable with a "mutableStateOf by remember"

**Comment by jh115424** [comment]
yes, I actually got that the when statements!

My issue is do I need to have the navigation code implemented and how I would write the click code in the brackets so it clicks from one to another.



Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:5e5ef0bc-355a-44dd-9055-2ee347053227]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by YaerQ** [comment]
`Button(onClick = {onNextClick()}, modifier = Modifier.width(100.dp)) {
                Text(text = "Next")
            }`

I hoisted the `onClick` to a Parameter I made `onNextClick()` in the composable. I assigned `() -> Unit` as the type to that parameter so I can input a lambda function (I think that's what's called). That way when I call the composable in the `when` expression I can assign different behavior to the button depending on which state the `var currentImage by remember {mutableStateOf(1)}` is. Remeber that each state represent an image composable. For example for the first image the `currentImage`  state is at 1. So I want the next button to change it to state 2 and the previous button to change it to state 5 because I have 5 images.

```
 when (currentImage) {

            1 -> {
                ArtWithArtistCard(
                    artworkTitle = "Too Many Leaves on My Face",
                    artworkArtist = "Leavy Forrest",
                    artworkYear = "(2008)",
                    imageResourceId = R.drawable.image1,
                    imageDescriptionTextId = R.string.app_name,
                    onNextClick = {currentImage = 2},
                    onPreviousClick = {currentImage = 5}
                )
            }
```  
As you can see I passed a lambda expression on the `onNextClick`  and on the `onPreviousClick` that will set `currentImage` to 2 when I click the next button and to 5 when I click the previous button.  Then I do the same to the other composables chaning the button behavior accordingly. 

```
when (currentImage) {

            1 -> {
                ArtWithArtistCard(
                    artworkTitle = "Too Many Leaves on My Face",
                    artworkArtist = "Leavy Forrest",
                    artworkYear = "(2008)",
                    imageResourceId = R.drawable.image1,
                    imageDescriptionTextId = R.string.app_name,
                    onNextClick = {currentImage = 2},
                    onPreviousClick = {currentImage = 5}
                )
            }

            2 -> {
                ArtWithArtistCard(
                    artworkTitle = "Kitty Cat",
                    artworkArtist = "Kat Jennings",
                    artworkYear = "(2018)",
                    imageResourceId = R.drawable.image2,
                    imageDescriptionTextId = R.string.app_name,
                    onNextClick = {currentImage = 3},
                    onPreviousClick = {currentImage = 1}
                )
            }

            3 -> {
                ArtWithArtistCard(
                    artworkTitle = "Are Fish Real?",
                    artworkArtist = "Sean Tunalo",
                    artworkYear = "(2020)",
                    imageResourceId = R.drawable.image3,
                    imageDescriptionTextId = R.string.app_name,
                    onNextClick = {currentImage = 4},
                    onPreviousClick = {currentImage = 2}
                )
            }

            4 -> {
                ArtWithArtistCard(
                    artworkTitle = "Ruining Mom's Garden",
                    artworkArtist = "Potter Green",
                    artworkYear = "(2019)",
                    imageResourceId = R.drawable.image4,
                    imageDescriptionTextId = R.string.app_name,
                    onNextClick = {currentImage = 5},
                    onPreviousClick = {currentImage = 3}
                )
            }

            5 -> {
                ArtWithArtistCard(
                    artworkTitle = "It's not Even Raining",
                    artworkArtist = "Rihanna",
                    artworkYear = "(2010)",
                    imageResourceId = R.drawable.image5,
                    imageDescriptionTextId = R.string.app_name,
                    onNextClick = {currentImage = 1},
                    onPreviousClick = {currentImage = 4}
                )
            }
        }
```

**Comment by YaerQ** [comment]
It depends on the order you wrote the properties in your composable

**Comment by jh115424** [comment]
hmmmmm......for some reason I get a unresolved reference for the onNextClick, even though I have it up in my string at the top...

I'll keep trying things.

I sent a screenshot in this email.



Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:5205c7c9-9847-4187-b4e3-cb902eab3625]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by YaerQ** [comment]
I can't see the screenshot. Make sure in the button onClick to write it as `onNextClick()` with the parentesis

**Comment by jh115424** [comment]
Ok, I'll send in github...

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jh115424** [comment]
I just sent it.  it is reply to another email in github


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:47d6cfca-8375-4060-88bd-62adfe562f12]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by YaerQ** [comment]
No, sorry still can't find the screenshot, you can copy paste the code here using the add code button <> (or crtl+e) which will be easier to check too.

**Comment by jh115424** [comment]
I sent it.

I also sent an issue about the alignment in a new question in Github.



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by YaerQ** [comment]
I'm sorry but where are you sending it? If you are replying to the github notification email with the code that wont work you have to post it here directly.

**Comment by jh115424** [comment]
Button(onClick = {onNextClick()}, modifier = Modifier.width(100.dp)

){

Text(text = "Next")

}


onNextClick comes up red and says, "unresolved reference", even though I have it in my when statements.



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by YaerQ** [comment]
Did you add `onNextClick: () - > Unit` as a property of the composable function you are using? 

Ex. 

```
@Composable
fun ArtistCard (onNextClick: () -> Unit ) {

....

}

```

This video should explain it more clearly 
[
https://www.youtube.com/watch?v=mymWGMy9pYI](url)
It explains how to save and change state and state hoisting.

**Comment by jh115424** [comment]
The is the Composable it is under......

would I do a composable JUST for the Button, because when I put the onClick in the
parenthesis for  fun ArtSpaceAppPreview, it turned the @Preview(showBackground = true red.



@Preview(showBackground = true)
@Composable
fun ArtSpaceAppPreview() {
    ArtSpaceAppTheme {
        Column {
            Row(modifier = Modifier
                .shadow(elevation = 5.dp)
                .border(width = 4.dp, color = Color.Blue)
                .padding(15.dp))
            {
                Image(
                    painter = painterResource(R.drawable._0220621_204734),
                    contentDescription = null)
            }
            Card(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(15.dp)
                    .clickable { },
                elevation = 10.dp

            ) {
                Column(
                    modifier = Modifier.padding(15.dp)



Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:56fd4bc4-76f3-4217-8488-94f11daa210d]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
this is what I have so far for The Button...and also still red line under Alignment.BottomStart, even though I have it under Row.




@Composable

fun Button(onNextClick: () -> Unit){
Row(
    horizontalArrangement = Arrangement.Start,
    verticalAlignment = Alignment.CenterVertically,
    modifier = Modifier
        .width(100.dp)
        .weight(1f)
        .align(alignment = Alignment.BottomStart)
){
    Button(onClick = {onNextClick }, modifier = Modifier.width(100.dp)) {
        Text(text = "Next")
    }
    Button(onClick = { }) {

    }

    }
}




Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:dec0a578-32af-4a6c-9a97-0e80e195d0ca]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by YaerQ** [comment]
Ok you should give the `onNextClick: () -> Unit` property to the parent composable not directly to the button. In the button then you pass that property to the `onClick` like this `onClick = {onNextClick()}`

**Comment by jh115424** [comment]
uh oh.....

I think the parent composable is mixed with the code of the first Art image.

What can I do to unmix it?




@Preview(showBackground = true)
@Composable
fun ArtSpaceAppPreview() {
    ArtSpaceAppTheme {
        Column {
            Row(modifier = Modifier
                .shadow(elevation = 5.dp)
                .border(width = 4.dp, color = Color.Blue)
                .padding(15.dp))
            {
                Image(
                    painter = painterResource(R.drawable._0220621_204734),
                    contentDescription = null)
            }
            Card(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(15.dp)
                    .clickable { },
                elevation = 10.dp

            ) {
                Column(
                    modifier = Modifier.padding(15.dp)

                ) {
                    Text(text = "Lady Of Glamour")
                    Spacer(modifier = Modifier
                        .height(20.dp)
                        .padding(15.dp)



Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:b054344e-8d74-4540-b96a-9d7290890b3f]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by YaerQ** [comment]
You may want to reorganize the code then:
MainApp Composable -> The Main parent where the component composables will go
Component Composable -> where the different element composble will go... Image, Text, Button. You want to give the properties to this one.

then call the main composable inside the Set Content, and the Preview. If you check out the code I posted the structure I used is there.

**Comment by jh115424** [comment]
Now I would do a new composable for each picture, right?     NOT with preview, just regular composable?

I got the main one at the top with the preview with no code!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by YaerQ** [comment]
No, make one composable with the state hoisting and re use it for the different pictures. 

In the preview just call the main composable so you can preview it like this 
```
@Preview(showBackground = true)
@Composable
fun ArtSpaceAppPreview() {
    ArtSpaceAppTheme {
        NameOfYourMainComposable()
    }
}
```

**Comment by jh115424** [comment]
ok, so I just repeat that one main composable for each picture shown below, or something similar to it right?


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:b7b1fcbf-c95e-4dd3-b978-c2cd0dfd50f1]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by YaerQ** [comment]
Yes, if you hoist the state  meaning if you add the information you need as properties to the composable function you can re use the composable. 

What are those properties? Well, you need an image, the image description (for screen readers accessibility) the art name, the artist name, the year it was created/finished, and the function of the button. So your coposable function should look like this:
(Remember you can call the properties however you want, the names I use here are just an example same with the layout of the composable. Whats Important is the type you assign them and the order because when you use the composable it will ask the values for the properties in the same order you typed them.)


```
@Composable
fun ComponentComposable ( artImageId: Int, artDescriptionId: String , artName: String, artistName: String, artYear: String, onNextClick: () - > Unit, onPreviousClick: () - >) {

Column {
Image(
       painter = painterResource(artImageId),   //Here you pass the property you created instead of the image resource directly
       contentDescription = stringResource(artDescriptionId), //Here you pass the artDescription property
       contentScale = ContentScale.FillWidth,
      modifier = Modifier
      .padding(36.dp)
      .fillMaxWidth()
     )

//You do the same for the text and the buttons

Text(
         text = artistName,    // Pass the artistName property
         fontSize = artistFontSize,
         fontWeight = FontWeight.Bold,
         modifier = Modifier.padding(end = 4.dp)
         )
         
        Text(
                text = artYear, // Pass the artYear property 
                fontSize = 16.dp
       )
                                    //Pass the onNextClick lambda here
Button(onClick = { onNextClick() }, modifier = Modifier.width(100.dp)) {
                Text(text = "Next")
            }

}       

```
Now you can call this ComponentComposable as many times you want and just pass the values the properties need. For example:

```
@Composable
fun MainApp () {

ComponentComposable (
            artImageId = R.drawable.image1 // or the name you gave the image file
            artDescriptionId = "Description of the image"
            artName = "Name of the piece"
            artistName = "Name of the Artist"
            artYear = "Art Year"
            onNextClick = { variable = 2 }  // here you pass the function you want the button to have.  in this case it will set the variable          
                                                          to 2 when you click the button.
            onPreviousClick = {5}  //same as onClick in this case it will set the variable to 5 so it goes to the last image (if you only have              
                                              5 images) 
)
                         
// for the second image and the third etc etc you just call the ComponentComposable  again and pass the information for the respective image. 

ComponentComposable (
            artImageId = R.drawable.image2
            artDescriptionId = "Description of the second image"
            artName = "Name of the second piece"
            artistName = "Name of the second Artist"
            artYear = "Art Year of the second image"
            onNextClick = { variable = 3 }            
            onPreviousClick = {variable = 1}                                                   
) 


}
```

if you used `when` then it should look like: 

```
@Composable
fun MainComposable() {

when (variable) { 

1 - >  ComponentComposable (
            artImageId = R.drawable.image1 // or the name you gave the image file
            artDescriptionId = "Description of the image"
            artName = "Name of the piece"
            artistName = "Name of the Artist"
            artYear = "Art Year"
            onNextClick = { variable = 2 }  // here you pass the function you want the button to have.  in this case it will set the variable to 2 when you click the button.
            onPreviousClick = {5}  //same as onClick in this case it will set the variable to 5 so it goes to the last image (if you only have 5 images) 
)

2 - > ComponentComposable etc etc...
```

**Comment by YaerQ** [comment]
No problem! 🙂

**Comment by jh115424** [comment]
ok, now don't laugh!    ( well, you can laugh, because I laughed also. lol)

I started rearranging everything, and I got the 1st image, so I know I am on the right track, buuuuuuuut....it is really tiny.

It is the same code I used originally for the 1st image I showed you......dont know what I am missing.



@Composable

fun ArtistWithCard(artTitle: String,
                   artArtists: String,
                   artYear: String,
                   imageResource: Int,
                   imageDescriptionTextId: Int,
                   onNextClick: () -> Unit,
                   onPreviousClick: () -> Unit
) {
    val artistsFontSize = 14.sp

    Column(
        modifier = Modifier.fillMaxSize(),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.SpaceBetween
    ){
        Image(painter = painterResource(R.drawable._0220621_204734),
            contentDescription =null,
            modifier = Modifier
                .shadow(elevation = 20.dp)
                .border(width = 4.dp, color = Color.Blue)
                .size(15.dp)
        )

       }
    }



Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:d761e740-54e4-4141-9a1b-543bc73a545b]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by YaerQ** [comment]
Can you send all the code? From the Import to the last line on the bottom. It would make it easier to check whats wrong.

**Comment by jh115424** [comment]
Yes, I figured it out!    Its back to normal!

I kept working with it!

Thx!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jh115424** [comment]
Hi Yaer!   Hope your having a great weekend!

Well I am about finished with the 1st art piece after the revisions....finally!

I forgot one thing....how do I add space UNDER the card so I can put the buttons?


[cid:fcd483d3-baaa-473f-b995-d28d6eb1bdaa]


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:213eed01-1c6e-464c-9737-596f42af664a]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
nevermind.....I got it!   🙂


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:75f614c8-8aca-4c0f-9ddb-1d365c504fd0]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by YaerQ** [comment]
Either with a spacer or padding

**Comment by YaerQ** [comment]
Oh I missed the post saying you got it. Glad you got it! 🙂

**Comment by jh115424** [comment]
thanks!      Great news......I am FINISHED, and the art pieces change back and forth successfully in the Interactive mode😀, BUUUUUTTTT, it gives a error when I try to upload it to my phone.😩


There are no errors in the code or anything.    I don't know what they mean by "Duplicate class.

Here is the screen shot.




Jennifer Hodge

[cid:6f3015b7-d240-4317-809f-6a5038dc8666]Internet Sales

414-586-5425

Russ Darrow Honda


[cid:56875bbf-4221-40bb-a459-572efeae477d]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
nevermind, figured out the last issue!    I had a duplicate line in the module gradles


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:413045d7-7518-4f6f-9f23-30a264348f6f]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
So, what regular Kotlin (non compose) projects are you working on?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by YaerQ** [comment]
I just started learning Kotlin a few weeks ago (like a week before I replied to your original post), so far I'm just doing the codelabs and other tutorials when I can. I bought two kotlin courses in udemy and I'll do those after I finish all the codelabs.

**Comment by YaerQ** [comment]
12.99 each on sale.  "The Complete Kotlin Course - Mastering Kotlin from Zero" I started this one yesterday. This one is basic kotlin/OOP programing in general, most of the programs exercises in this course run on the console not on the emulator/phone. 
The other one is "The Complete Android 12 Developer Course - Mastering Android" this is more advance and it teaches you how to make actual apps and how to use compose, databases, API's, audio/ video etc in your apps. This one I think it has 2 projects, one is a movie app and the other one is a WhatApp like messenger app.

**Comment by jh115424** [comment]
Can you send me the link?


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:4a3eb253-cbef-4fc3-b990-931a2e205089]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
I found it!

I am going to get the entire course for just $16.99!

That is a better deal!


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:d9a3c448-79c3-4cbf-b146-fbd33d4ff843]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by YaerQ** [comment]
https://www.udemy.com/course/the-complete-kotlin-course-mastering-kotlin-from-zero/
https://www.udemy.com/course/the-complete-android-10-developer-course-mastering-android/

**Comment by YaerQ** [comment]
> I found it! I am going to get the entire course for just $16.99! That is a better deal!
>
Oh Nice, yeah udemy always has some kind of sale going on

**Comment by jh115424** [comment]
This masterclass is very informative!

I'm about to start the 1st project and he explains things well!    The quizzes help too!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jh115424** [comment]
you know what....I have to check on that.  I will and watch the vid when I go on my break!

thanks!


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:3e5b73e2-0263-4301-8a87-4b593ff3807a]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
I am also in the process of trying to do the Art Space App in regular Kotlin code to see what I learned so far and to show in my portfolio I can do the same project in both codes!


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:fb78c926-2e53-4005-8eaa-d4255902b4d8]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
Button(onClick = {onNextClick()}, modifier = Modifier.width(100.dp)

){

Text(text = "Next")

}


onNextClick comes up red and says "unresolved reference", even though I have it in my when statements.






Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:c44b47bb-66ed-4dfa-8cbd-da17df81c024]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
one last thing.....How do I set up a cover page?

I loaded it onto my cell, but the first page is blank with no way to click to the next art piece


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:0ea6d9c2-2b40-4581-acab-9ee9c353fb08]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
hey, where did you get Image Surface?  Doesn't seem to be a selection.


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:8d14184d-8ec5-4503-b329-483f08de6a0f]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
ooooooooo!          I get paid Friday, so I certainly will get those!

Can you send me the link?


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:587a3c2a-a0f1-4d37-a58c-c94a3c5b8ed0]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
I am confused on one thing though.......where did ComponentComposable come from?

I typed that, and it was red.

I thought you said to reuse this for the other pieces......

@Composable

fun ArtistWithCard(artTitle: String,
                   artArtists: String,
                   artYear: String,
                   imageResourceId: Int,
                   imageDescriptionTextId: Int,
                   onNextClick: () -> Unit,
                   onPreviousClick: () -> Unit


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:4ec9d0d5-e236-495d-ad29-43d6fb9b0854]<https://your.tradeinvalet.com/tdhe0j>

________________________________
