### ISSUE TITLE
Write conditionals in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by JayKisore** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#90]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-conditionals#0

**In which task and step of the codelab can this issue be found?**
1st - Before you begin

**Describe the problem**
Two bullet points are repeated under what you will learn section. 2nd and 3d bullet points are repeated.

**Steps to reproduce?**
1. Go to...https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-conditionals#0
2. Click on...
3. See error...
![Screenshot 2023-08-13 232501](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/assets/6451688/8101d4e6-9d31-4157-a44a-d52aaa72b350)

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by hassan0599** [comment]
Hi @JayKisore, although it might seem like it but this is not a mistake. The difference between statements and expressions is that expressions produce a value which can be assigned to a variable while statements do not produce a value.

**Comment by JayKisore** [comment]
> Hi @JayKisore, although it might seem like it but this is not a mistake. The difference between statements and expressions is that expressions produce a value which can be assigned to a variable while statements do not produce a value.
Yes you are right.
