### ISSUE TITLE
Use the debugger in Android Studio: Android Basics with Compose

### ISSUE THREAD

**Issue by gracchen** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#91]
I git cloned the dice roller app example and ran it on Android Studio Giraffe 2022.3.1 in an API 28 emulator. If I just run the app the app works. However, when I try to follow the last section "Inspect variables" 
 in [Use the debugger](https://developer.android.com/codelabs/basic-android-kotlin-compose-intro-debugger?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-intro-debugger#4) by clicking resume after placing one breakpoint at 

val imageResource = when(result) {   

and clicking "debug", the debugger stops again at imageResource instead of allowing the app to run as the tutorial expects. The result is instead this:
![image_2023-09-05_085823566](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/assets/103862883/0ba03a05-68d3-4679-abaf-32a3ed4f70ad)

So I click resume again and now the debugger is just stuck at "Waiting until last debugger command completes" screen while the emulator screen remains white and blank the entire time. 
![image_2023-09-05_085911503](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/assets/103862883/5864cacb-6d05-4131-a55f-92919b08b874)

The same thing happens when I step over at the 2nd hit at imageResource. When I keep stepping in and out starting from the first breakpoint hit, I notice this waiting message first appears at MaterialTheme.kt line 81 

        ProvideTextStyle(value = typography.bodyLarge, content = content)

![image_2023-09-05_090639109](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/assets/103862883/4c0a7857-e166-489e-990b-6d74fcad5daa)

I have tried restarting the IDE but it doesn't fix it. Any tips would be appreciated.

**Comment by johnshea** [comment]
Hi @gracchen 

Thank you for writing in.

I have not seen or heard of the issue you are experiencing.

I would suggest updating Android Studio to the latest stable version and try completing the lesson again.

Regards.
