### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by feesgo** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#94]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#2

**In which task and step of the codelab can this issue be found?**

Restructure the sample code

**Describe the problem**

It says:

"Restructure the sample code
You need to change some of the generated code to more closely resemble the theme of a dice roller app.

As you saw in the screenshot of the final app, there's an image of a dice and a button to roll it. You will structure the composable functions to reflect this architecture.

To restructure the sample code:

Remove the DefaultPreview() function."

But the DefaultPreview() function. does not exist...

There is:

@Composable
fun Greeting(name: String, modifier: Modifier = Modifier) {
    Text(
        text = "Hello $name!",
        modifier = modifier
    )
}

@Preview(showBackground = true)
@Composable
fun GreetingPreview() {
    DiceRollerTheme {
        Greeting("Android")
    }
}

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**

_Android Studio version:_ 

Android Studio Giraffe | 2022.3.1 Patch 1

_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/assets/44176819/d733a365-99da-4f8a-b7bd-81ca4b0fedd8)

**Comment by johnshea** [comment]
Hi @feesgo 

Thank you for writing in and bringing this to our attention.

The lesson has been updated and will be republished again in the near future with the fix.

Hope you are enjoying the course!

Regards.
