### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by parth10102** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#96]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-build-a-dice-roller-app?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-build-a-dice-roller-app#5

**URL of github**
https://raw.githubusercontent.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/main

**In which task and step of the codelab can this issue be found?**
In the 6th step: Add an Image.

**Describe the problem**
When asked to download the zip file containing the images of the dice the url doesn't open and shows the error:
"400: Invalid request". 

**Additional information**

<img width="821" alt="Screenshot 2023-09-29 172248" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/assets/111889061/dd9e7d6c-0400-41ea-9ef3-f8c83a91b1c2">

**Comment by johnshea** [comment]
Hi @parth10102 

Thank you for writing in.

Please try the link again as it is currently working.

Hope you are enjoying the course!

Regards.
