### ISSUE TITLE
Use nullability with Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by alisherotajonov866** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#97]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-nullability?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-nullability#2

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

I think the symbol was written incorrectly first line -> "Previously, you learned to use...."
 because, now we see the symbol in here (.) but i'm sure it will be (?) 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @alisherotajonov866 

Thank you for writing in and raising your concern with us.

I will share with the team so they can review and revise the lesson as needed.

Hope you are enjoying the course!

Regards.
