### ISSUE TITLE
Practice problems Unit 2 Pathway 1: Android Basics with Compose

### ISSUE THREAD

**Issue by DarakDuVal** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#98]
A ---
name: Practice problems unit 2 pathway 1 issue template
about: Issue template for Unit 1 | Pathway 1 | Practice Problems
title: 'Practice problems Unit 2 Pathway 1: Android Basics with Compose'
labels: ''
assignees: ''

---

**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
Foldable phone has logical error in which screen light should turn off when folded

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Victor-Agbo** [comment]
Yes, the main, large screen of the phone should be turned off when folded.

**Comment by johnshea** [comment]
Hi @DarakDuVal 

Thank you for writing in and bringing this issue to our attention.

I will share it with the team so they can decide how they want to address it.

Hope you are enjoying the course.

Regards.
